// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

    [Serialized] // Tells the save/load system this object needs to be serialized. 
    [LocDisplayName("Animal Waste")] // Defines the localized name of the item.
    [Weight(250)] // Beet=100 Stew=600
    [Ecopedia("Natural Resources", "Animal", createAsSubPage: true)]
    [LocDescription("A byproduct of butchering animals. Mostly bones and organs.")] //The tooltip description for the food item.
    public partial class AnimalWasteItem : Item
    {
		
    }

}