// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Wires;




    //FoodItem


    [Serialized]
    [LocDisplayName("Bag of Caramel Taffy")]
    [Weight(200)]
    [Tag("Food")]
    [Ecopedia("Food", "CATEGORY", createAsSubPage: true)]
    [LocDescription("ITEM DESCRIPTION.")]
    public partial class CaramelTaffyItem : FoodItem
    {

        public override float Calories => 500;

        public override Nutrients Nutrition => new Nutrients()

        {
            Carbs = 20,
            Fat = 10,
            Protein = 2,
            Vitamins = 1
        };

        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72);

    }




    //Recipe


    [RequiresSkill(typeof(CuttingEdgeCookingSkill), 1)]
    [Ecopedia("Food", "Sweets", subPageName: "Bag of Caramel Taffy Item")]
    public partial class CaramelTaffyRecipe : RecipeFamily
    {
        public CaramelTaffyRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "CaramelTaffy",  //noloc
                displayName: Localizer.DoStr("Bag of Caramel Taffy"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(SugarItem), 30, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)),  // Base ingredient for caramel
                    new IngredientElement(typeof(ButterItem), 10, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)), // Butter for creaminess
                    new IngredientElement(typeof(CreamItem), 5, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)), // For richness and texture
                    new IngredientElement(typeof(SaltItem), 1, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)), // To enhance flavor
                    new IngredientElement(typeof(HoneyItem), 2, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)), // Adds a natural sweetness
                    new IngredientElement(typeof(HighFructoseCornSyrupItem), 5, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)), // Ensures the taffy is chewy
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<CaramelTaffyItem>(5),
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 1;

            this.LaborInCalories = CreateLaborInCaloriesValue(500, typeof(CuttingEdgeCookingSkill));

            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(CaramelTaffyRecipe),
                start: 5f,
                skillType: typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingFocusedSpeedTalent), typeof(CuttingEdgeCookingParallelSpeedTalent));

            this.ModsPreInitialize();

            this.Initialize(displayText: Localizer.DoStr("Bag of Caramel Taffy"), recipeType: typeof(CaramelTaffyRecipe));

            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(TABLENAMEObject), recipe: this);

        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
