// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
using Eco.Shared.Utils;
using Eco.Shared.Time;
using System;
using System.Collections.Generic;
using Eco.Gameplay.Components;
using Eco.Gameplay.DynamicValues;
using Eco.Gameplay.Skills;
using Eco.Shared.Items;
using Eco.World;
using Eco.World.Blocks;
using Gameplay.Systems.TextLinks;
using Eco.Core.Controller;
using Eco.Gameplay.Settlements.ClaimStakes;
using Eco.Gameplay.Items.Recipes;

[Serialized]
[LocDisplayName("Caramel Taffy")]
[Weight(250)]
[Ecopedia("Food", "Sweets", createAsSubPage: true)]
[LocDescription("A chewy and sweet candy that is perfect for all occasions.")]
public partial class CaramelTaffyItem : FoodItem
{
    public override float Calories => 500; // Caramel Taffy typically has high sugar content, but less than some other candies
    public override Nutrients Nutrition => new Nutrients() 
    { 
        Carbs = 20, 
        Fat = 10, 
        Protein = 2, 
        Vitamins = 0
    };

    protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72); // Shelf life of 72 hours (3 days)
}

[RequiresSkill(typeof(CuttingEdgeCookingSkill), 2)] // Requires a slightly higher skill level for this more complicated recipe
public partial class CaramelTaffyRecipe : RecipeFamily
{
    public CaramelTaffyRecipe()
    {
        var recipe = new Recipe();
        recipe.Init(
            name: "CaramelTaffy", 
            displayName: Localizer.DoStr("Caramel Taffy"), 
            ingredients: new List<IngredientElement>
            {
                new IngredientElement(typeof(SugarItem), 30, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)),  // Base ingredient for caramel
                new IngredientElement(typeof(ButterItem), 10, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)), // Butter for creaminess
                new IngredientElement(typeof(CreamItem), 5, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)), // For richness and texture
                new IngredientElement(typeof(SaltItem), 1, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)), // To enhance flavor
                new IngredientElement(typeof(HoneyItem), 2, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)), // Adds a natural sweetness
                new IngredientElement(typeof(HighFructoseCornSyrupItem), 5, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)), // Ensures the taffy is chewy
            },
            products: new List<CraftingElement>
            {
                new CraftingElement<CaramelTaffyItem>(6), // Makes 6 pieces of caramel taffy
            });

        this.Recipes = new List<Recipe> { recipe };
        this.ExperienceOnCraft = 1; // Provides crafting experience upon making Caramel Taffy

        this.LaborInCalories = CreateLaborInCaloriesValue(500, typeof(CuttingEdgeCookingSkill)); // Adjusts labor cost based on skill

        this.CraftMinutes = CreateCraftTimeValue(
            beneficiary: typeof(CaramelTaffyRecipe),
            start: 5f, // Time to craft the taffy
            skillType: typeof(CuttingEdgeCookingSkill),
            typeof(CuttingEdgeCookingFocusedSpeedTalent),
            typeof(CuttingEdgeCookingParallelSpeedTalent));

        this.ModsPreInitialize();
        this.Initialize(displayText: Localizer.DoStr("Caramel Taffy"), recipeType: typeof(CaramelTaffyRecipe)); // Display name in the crafting UI
        this.ModsPostInitialize();

        CraftingComponent.AddRecipe(tableType: typeof(StoveObject), recipe: this); // Adds this recipe to the stove
    }

    partial void ModsPreInitialize();
    partial void ModsPostInitialize();
}
