// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

    [Serialized] // Tells the save/load system this object needs to be serialized. 
    [LocDisplayName("ITEM NAME")] // Defines the localized name of the item.
    [Weight(100)] // Beet=100 Stew=600
    [Ecopedia("Items", "Products", subPageName: "ITEM NAME Item")]
    [LocDescription("ITEM DESCRIPTION.")] //The tooltip description for the food item.
    public partial class ITEMNAMEItem : Item
    {


    }


    [RequiresSkill(typeof(SKILLNAMESkill), 1)]
    public partial class ITEMNAMERecipe : RecipeFamily
    {
        public ITEMNAMERecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "ITEMNAME",  //noloc
                displayName: Localizer.DoStr("RECIPE NAME"),

                // Defines the ingredients needed to craft this recipe. An ingredient items takes the following inputs
                // type of the item, the amount of the item, the skill required, and the talent used.
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(INGREDIENTNAMEItem), 1, typeof(SKILLNAMESkill), typeof(SKILLNAMELavishResourcesTalent)),
                    new IngredientElement("INGREDIENTTAG"), 1, typeof(SKILLNAMESkill), typeof(SKILLNAMELavishResourcesTalent)),
                    new IngredientElement(typeof(INGREDIENTNAMEItem), 1, true),
                },

                // Define our recipe output items.
                // For every output item there needs to be one CraftingElement entry with the type of the final item and the amount
                // to create.
                items: new List<CraftingElement>
                {
                    new CraftingElement<ITEMNAMEItem>(6)
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 0.5f; // Defines how much experience is gained when crafted.

            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(15, typeof(SKILLNAMESkill));

            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(ITEMNAMERecipe), start: 1f, skillType: typeof(SKILLNAMESkill), typeof(SKILLNAMEFocusedSpeedTalent), typeof(SKILLNAMEParallelSpeedTalent));

            // Perform pre/post initialization for user mods and initialize our recipe instance with the display name "Charred Beet"
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("RECIPE NAME"), recipeType: typeof(ITEMNAMERecipe));
            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system so it ITEMNAME be crafted.
            CraftingComponent.AddRecipe(tableType: typeof(TABLENAMObject), recipe: this);
        }

        partial void ModsPreInitialize();

        partial void ModsPostInitialize();
    }
}