// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

    [RequiresSkill(typeof(CookingSkill), 4)]  // 2
    [Ecopedia("Food", "Cooking", subPageName: "Simmered Meat Small Bulk Item")]
    public partial class SimmeredMeatBulkRecipe : RecipeFamily
    {
        public SimmeredMeatBulkRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "SimmeredMeatSmallBulk",  //noloc
                displayName: Localizer.DoStr("Simmered Meat Small Bulk"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(PreparedMeatItem), 20, typeof(CookingSkill), typeof(CookingLavishResourcesTalent)),  // 2 x 10
                    new IngredientElement(typeof(MeatStockItem), 10, typeof(CookingSkill), typeof(CookingLavishResourcesTalent)),  // 1 x 10
                },
                items: new List<CraftingElement>
                {
                    new CraftingElement<SimmeredMeatItem>(20)  // 1 x 10 x 2
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 10; // 1 x 10
            this.LaborInCalories = CreateLaborInCaloriesValue(250, typeof(CookingSkill));  // 25 x 10
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(SimmeredMeatBulkRecipe), start: 40, skillType: typeof(CookingSkill), typeof(CookingFocusedSpeedTalent), typeof(CookingParallelSpeedTalent));  // 4 x 10
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Simmered Meat Small Bulk"), recipeType: typeof(SimmeredMeatBulkRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(tableType: typeof(CastIronStoveObject), recipe: this);
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}