// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from BlockTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Core.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.SharedTypes;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.World.Water;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;
	// added lines
	using Eco.Core.Plugins.Interfaces;
	using Eco.Core.Plugins;
	using Eco.Core.Utils;
    using Eco.Shared.Math;


    [RequiresSkill(typeof(AdvancedMasonrySkill), 3)]	// 1
    [Ecopedia("Blocks", "Building Materials", subPageName: "Ashlar Basalt Bulk Item")]
    public partial class AshlarBasaltBulkRecipe : RecipeFamily
    {
        public AshlarBasaltBulkRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "AshlarBasaltBulk",  //noloc
                displayName: Localizer.DoStr("Ashlar Basalt Bulk"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(BasaltItem), 500, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),		// 20 x 25
                    new IngredientElement(typeof(MortarItem), 150, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),		// 6 x 25
                    new IngredientElement(typeof(SteelBarItem), 25, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),	// 1 x 25
                },
                items: new List<CraftingElement>
                {
                    new CraftingElement<AshlarBasaltItem>(75),  // 1 x 25 x 3 Boosted
                    new CraftingElement<CrushedBasaltItem>(typeof(AdvancedMasonrySkill), 150, typeof(AdvancedMasonryLavishResourcesTalent)),	// 2 x 25 x 3
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 37.5f;		// 1.5 x 25
            this.LaborInCalories = CreateLaborInCaloriesValue(4500, typeof(AdvancedMasonrySkill));	// 180 X 25
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(AshlarBasaltBulkRecipe), start: 16f, skillType: typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryFocusedSpeedTalent), typeof(AdvancedMasonryParallelSpeedTalent));	// 0.64 x 25
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Ashlar in Bulk"), recipeType: typeof(AshlarBasaltBulkRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(tableType: typeof(AdvancedMasonryTableObject), recipe: this);
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }

    [Ecopedia("Blocks", "Building Materials", subPageName: "Ashlar Shale Bulk Item")]
    public partial class AshlarShaleBulkRecipe : Recipe
    {
        public AshlarShaleBulkRecipe()
        {
            var recipe = new Recipe();
            this.Init(
                name: "AshlarShaleBulk",  //noloc
                displayName: Localizer.DoStr("Ashlar Shale Bulk"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(ShaleItem), 500, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),		// 20 x 25
                    new IngredientElement(typeof(MortarItem), 150, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),		// 6 x 25
                    new IngredientElement(typeof(SteelBarItem), 25, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),	// 1 x 25
                },
                items: new List<CraftingElement>
                {
                    new CraftingElement<AshlarShaleItem>(75),	// 1 x 25 x 3 Boosted
                    new CraftingElement<CrushedShaleItem>(typeof(AdvancedMasonrySkill), 150, typeof(AdvancedMasonryLavishResourcesTalent)),	// 2 x 25 x 3
                });
            CraftingComponent.AddTagProduct(typeof(AdvancedMasonryTableObject), typeof(AshlarBasaltBulkRecipe), this);
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }

    [Ecopedia("Blocks", "Building Materials", subPageName: "Ashlar Limestone Bulk Item")]
    public partial class AshlarLimestoneBulkRecipe : Recipe
    {
        public AshlarLimestoneBulkRecipe()
        {
            var recipe = new Recipe();
            this.Init(
                name: "AshlarLimestoneBulk",  //noloc
                displayName: Localizer.DoStr("Ashlar Limestone Bulk"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(LimestoneItem), 500, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),		// 20 x 25
                    new IngredientElement(typeof(MortarItem), 150, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),			// 6 x 25
                    new IngredientElement(typeof(SteelBarItem), 25, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),		// 1 x 25
                },
                items: new List<CraftingElement>
                {
                    new CraftingElement<AshlarLimestoneItem>(75),	// 1 x 25 x 3 Boosted
                    new CraftingElement<CrushedLimestoneItem>(typeof(AdvancedMasonrySkill), 150, typeof(AdvancedMasonryLavishResourcesTalent)),		// 2 x 25 x 3
                });
            CraftingComponent.AddTagProduct(typeof(AdvancedMasonryTableObject), typeof(AshlarBasaltBulkRecipe), this);
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }

    [Ecopedia("Blocks", "Building Materials", subPageName: "BulkAshlar Granite Bulk Item")]
    public partial class AshlarGraniteBulkRecipe : Recipe
    {
        public AshlarGraniteBulkRecipe()
        {
            var recipe = new Recipe();
            this.Init(
                name: "kAshlarGraniteBulk",  //noloc
                displayName: Localizer.DoStr("Ashlar Granite Bulk"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(GraniteItem), 500, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),	// 20 x 25
                    new IngredientElement(typeof(MortarItem), 150, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),	// 6 x 25
                    new IngredientElement(typeof(SteelBarItem), 25, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),	// 1 x 25
                },
                items: new List<CraftingElement>
                {
                    new CraftingElement<AshlarGraniteItem>(75),	// 1 x 25 x 3 Boosted
                    new CraftingElement<CrushedGraniteItem>(typeof(AdvancedMasonrySkill), 150, typeof(AdvancedMasonryLavishResourcesTalent)),	// 2 x 25 x 3
                });
            CraftingComponent.AddTagProduct(typeof(AdvancedMasonryTableObject), typeof(AshlarBasaltBulkRecipe), this);
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }

    [Ecopedia("Blocks", "Building Materials", subPageName: "BulkAshlar Gneiss Bulk Item")]
    public partial class AshlarGneissBulkRecipe : Recipe
    {
        public AshlarGneissBulkRecipe()
        {
            var recipe = new Recipe();
            this.Init(
                name: "AshlarGneissBulk",  //noloc
                displayName: Localizer.DoStr("Ashlar Gneiss Bulk"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(GneissItem), 500, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),		// 20 x 25
                    new IngredientElement(typeof(MortarItem), 150, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),		// 6 x 25
                    new IngredientElement(typeof(SteelBarItem), 25, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),	// 1 x 25
                },
                items: new List<CraftingElement>
                {
                    new CraftingElement<AshlarGneissItem>(75),	// 1 x 25 x 3 Boosted
                    new CraftingElement<CrushedGneissItem>(typeof(AdvancedMasonrySkill), 150, typeof(AdvancedMasonryLavishResourcesTalent)),	// 2 x 25 x 3
                });
            CraftingComponent.AddTagProduct(typeof(AdvancedMasonryTableObject), typeof(AshlarBasaltBulkRecipe), this);
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }

    [Ecopedia("Blocks", "Building Materials", subPageName: "BulkAshlar Sandstone Bulk Item")]
    public partial class AshlarSandstoneBulkRecipe : Recipe
    {
        public AshlarSandstoneBulkRecipe()
        {
            var recipe = new Recipe();
            this.Init(
                name: "AshlarSandstoneBulk",  //noloc
                displayName: Localizer.DoStr("Ashlar Sandstone Bulk"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(SandstoneItem), 500, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),	// 20 x 25
                    new IngredientElement(typeof(MortarItem), 150, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),		// 6 x 25
                    new IngredientElement(typeof(SteelBarItem), 25, typeof(AdvancedMasonrySkill), typeof(AdvancedMasonryLavishResourcesTalent)),	// 1 x 25
                },
                items: new List<CraftingElement>
                {
                    new CraftingElement<AshlarSandstoneItem>(75),	// 1 x 25 x 3 Boosted
                    new CraftingElement<CrushedSandstoneItem>(typeof(AdvancedMasonrySkill), 150, typeof(AdvancedMasonryLavishResourcesTalent)),	// 2 x 25 x 3
                });
            CraftingComponent.AddTagProduct(typeof(AdvancedMasonryTableObject), typeof(AshlarBasaltBulkRecipe), this);
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
