// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;


   

    //Item

    [Serialized] // Tells the save/load system this object needs to be serialized. 
    [LocDisplayName("ITEM NAME")] // Defines the localized name of the ITEMNAME.
    [Weight(300)] // Defines how heavy the ITEMNAME is.
    
    [Ecopedia("Food", "CATEGORY", createAsSubPage: true)]
    [LocDescription("ITEM DESCRIPTION.")] //The tooltip description for the food ITEMNAME.
    public partial class ITEMNAMEItem : FoodItem
    {


        /// <summary>The amount of calories awarded for eating the food ITEMNAME.</summary>
        public override float Calories => 0;
        /// <summary>The nutritional value of the food ITEMNAME.</summary>
        public override Nutrients Nutrition => new Nutrients() { Carbs = 0, Fat = 0, Protein = 0, Vitamins = 0 };

        /// <summary>Defines the default time it takes for this ITEMNAME to spoil. This value can be modified by the inventory this ITEMNAME currently resides in.</summary>
        protected override float BaseShelfLife => (float)TimeUtil.HoursToSeconds(72);
    }





    //Recipe




    [RequiresSkill(typeof(SKILLNAMESkill), 1)]
    [Ecopedia("Food", "TYPE OF FOOD", subPageName: "ITEM NAME Item")]
    public partial class ITEMNAMERecipe : RecipeFamily
    {
        public ITEMNAMERecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "ITEMNAME",  //noloc
                displayName: Localizer.DoStr("RECIPE NAME"),

                // Defines the ingredients needed to craft this recipe. An ingredient ITEMNAMEs takes the following inputs
                // type of the ITEMNAME, the amount of the ITEMNAME, the skill required, and the talent used.
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(INGREDIENTNAMEItem), 10, typeof(SKILLNAMESkill), typeof(SKILLNAMELavishResourcesTalent)),
                    new IngredientElement("INGREDIENTTAG", 1, typeof(SKILLNAMESkill), typeof(SKILLNAMELavishResourcesTalent)),
                    new IngredientElement(typeof(INGREDIENTNAMEItem), 10, true),
                },

                // Define our recipe output ITEMNAMEs.
                // For every output ITEMNAME there needs to be one CraftingElement entry with the type of the final ITEMNAME and the amount
                // to create.
                items: new List<CraftingElement>
                {
                    new CraftingElement<ITEMNAMEItem>(5),
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 1; // Defines how much experience is gained when crafted.

            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(800, typeof(SKILLNAMESkill));

            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(ITEMNAMERecipe), start: 6f, skillType: typeof(SKILLNAMESkill), typeof(SKILLNAMEFocusedSpeedTalent), typeof(SKILLNAMEParallelSpeedTalent));

            // Perform pre/post initialization for user mods and initialize our recipe instance with the display name "ITEMNAME"
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("RECIPE NAME"), recipeType: typeof(ITEMNAMERecipe));
            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system so it can be crafted.
            CraftingComponent.AddRecipe(tableType: typeof(TABLENAMEObject), recipe: this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();

        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }



}
