// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
	using Eco.Shared.Time;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

    [Serialized]
    [LocDisplayName("Honey")]
    [Weight(75)]
	[MaxStackSize(200)]
    [Ecopedia("Food", "Raw Meat", createAsSubPage: true)]
    [LocDescription("Natures sweet sweet nectar")]
    public partial class HoneyItem : FoodItem
    {

        public override LocString DisplayNamePlural     => Localizer.DoStr("Honey");

        public override float Calories                  => 50;
        public override Nutrients Nutrition             => new Nutrients() { Carbs = 0, Fat = 1, Protein = 7, Vitamins = 0};
        protected override float BaseShelfLife            => (float)TimeUtil.HoursToSeconds(96);
    }

}
