// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from RecipeTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

    [RequiresSkill(typeof(FarmingSkill), 2)]
    public partial class ScrapecombsandhoneyRecipe : RecipeFamily
    {
        public ScrapecombsandhoneyRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "Scrapecombsandhoney",  //noloc
                displayName: Localizer.DoStr("Scrape combs and honey"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(WorkerbeeItem), 20, typeof(FarmingSkill), typeof(FarmingLavishResourcesTalent)),
					new IngredientElement(typeof(HoneyCombItem), 5, true),
					

                },

                items: new List<CraftingElement>
                {
					new CraftingElement<WorkerbeeItem>(15),
                    new CraftingElement<HoneyCombItem>(5),
					new CraftingElement<BeeswaxItem>(1),
                    new CraftingElement<HoneyItem>(2),

                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 5; 

            this.LaborInCalories = CreateLaborInCaloriesValue(70, typeof(FarmingSkill));

            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(ScrapecombsandhoneyRecipe), start: 2, skillType: typeof(FarmingSkill), typeof(FarmingFocusedSpeedTalent), typeof(FarmingParallelSpeedTalent));

            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Scrape combs and honey"), recipeType: typeof(ScrapecombsandhoneyRecipe));
            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(ApiaryObject), recipe: this);
        }

        partial void ModsPreInitialize();

        partial void ModsPostInitialize();
    }
	

}
