// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from ItemTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
	using Eco.Shared.Time;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

    [RequiresSkill(typeof(FarmingSkill), 1)]
    [Ecopedia("Items", "Products", subPageName: "Workerbee Item")]
    public partial class WorkerbeeRecipe : RecipeFamily
    {
        public WorkerbeeRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "Workerbee",  //noloc
                displayName: Localizer.DoStr("Workerbee"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(QueenbeeItem), 1, typeof(FarmingSkill), typeof(FarmingLavishResourcesTalent)),
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<WorkerbeeItem>(10),
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 3;
            
            this.LaborInCalories = CreateLaborInCaloriesValue(180, typeof(FarmingSkill));

            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(WorkerbeeRecipe), start: 2, skillType: typeof(FarmingSkill), typeof(FarmingFocusedSpeedTalent), typeof(FarmingParallelSpeedTalent));

            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Workerbee"), recipeType: typeof(WorkerbeeRecipe));
            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(ApiaryObject), recipe: this);
        }

        partial void ModsPreInitialize();

        partial void ModsPostInitialize();
    }
    
    [Serialized]
    [LocDisplayName("Worker bee")]
    [Weight(50)]
	[MaxStackSize(200)]
    [Ecopedia("Items", "Products", createAsSubPage: true)]
    [LocDescription("Faithful worker bees that make and produce honey for there queen careful you dont crush them.")]
    public partial class WorkerbeeItem : FoodItem
    {
        public override LocString DisplayNamePlural     => Localizer.DoStr("Worker bees");
        public override float Calories                  => 0;
        public override Nutrients Nutrition             => new Nutrients() { Carbs = 0, Fat = 0, Protein = 0, Vitamins = 0};
        protected override float BaseShelfLife            => (float)TimeUtil.HoursToSeconds(96);
    }
}
