// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from WorldObjectTemplate.tt />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Core.Items;
	using Eco.Gameplay.Auth;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Components.Auth;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Economy;
    using Eco.Gameplay.Housing;
    using Eco.Gameplay.Interactions;
	using Eco.Gameplay.Interactions.Interactors;
    using Eco.Gameplay.Items;
	using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Modules;
    using Eco.Gameplay.Minimap;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Occupancy;
	using Eco.Gameplay.Placement;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Property;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
	using Eco.Gameplay.Systems.NewTooltip;
	using Eco.Shared.IoC;
    using Eco.Shared;
    using Eco.Shared.Math;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
	using Eco.Shared.SharedTypes;
    using Eco.Shared.Utils;
    using Eco.Shared.View;
    using Eco.Shared.Items;
    using Eco.Shared.Networking;
    using Eco.World.Blocks;
    using Eco.Gameplay.Civics.Objects;
    using Eco.Gameplay.Settlements;
    using Eco.Core.Controller;
    using Eco.Core.Utils;
	using Eco.Gameplay.Components.Storage;

    using Eco.Gameplay.Items.Recipes;

    [Serialized]
    [RequireComponent(typeof(PropertyAuthComponent))]
    [RequireComponent(typeof(MinimapComponent))]
    [RequireComponent(typeof(LinkComponent))]
    [RequireComponent(typeof(CraftingComponent))]
    [RequireComponent(typeof(PluginModulesComponent))]
    [RequireComponent(typeof(ForSaleComponent))]
    // added for storage
    [RequireComponent(typeof(PublicStorageComponent))]
    //[RequireComponent(typeof(StockpileComponent))]
    //[RequireComponent(typeof(WorldStockpileComponent))]


    [Tag("Usable")]
    [Ecopedia("Work Stations", "Craft Tables", subPageName: "CattleBarn Item")]
    public partial class CattleBarnObject : WorldObject, IRepresentsItem, IHasInteractions
    {
        [Serialized] public bool OpenDoors { get; set; }
        public virtual Type RepresentedItemType => typeof(CattleBarnItem);
        public override LocString DisplayName => Localizer.DoStr("Cattle Barn");
        public override TableTextureMode TableTexture => TableTextureMode.Brick;
		static CattleBarnObject() 
		{
 var BlockOccupancyList = new List<BlockOccupancy>
            {
                #region Occupancy
//////////////////////////////////////5x5x13//////////////////////////////////////
                                        //  W, H, L
			new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(1, 0, 0)),
            new BlockOccupancy(new Vector3i(2, 0, 0)),
            new BlockOccupancy(new Vector3i(3, 0, 0)),
            new BlockOccupancy(new Vector3i(4, 0, 0)),
			new BlockOccupancy(new Vector3i(5, 0, 0)),
			new BlockOccupancy(new Vector3i(6, 0, 0)),
			new BlockOccupancy(new Vector3i(7, 0, 0)),
			new BlockOccupancy(new Vector3i(8, 0, 0)),
		
            new BlockOccupancy(new Vector3i(0, 0, 1)),
//            new BlockOccupancy(new Vector3i(1, 0, 1)),
//            new BlockOccupancy(new Vector3i(2, 0, 1)),
//            new BlockOccupancy(new Vector3i(3, 0, 1)),
//            new BlockOccupancy(new Vector3i(4, 0, 1)),
//			new BlockOccupancy(new Vector3i(5, 0, 1)),
//			new BlockOccupancy(new Vector3i(6, 0, 1)),
//			new BlockOccupancy(new Vector3i(7, 0, 1)),
			new BlockOccupancy(new Vector3i(8, 0, 1)),
			

			new BlockOccupancy(new Vector3i(0, 0, 2)),
//            new BlockOccupancy(new Vector3i(1, 0, 2)),
//            new BlockOccupancy(new Vector3i(2, 0, 2)),
//            new BlockOccupancy(new Vector3i(3, 0, 2)),
//            new BlockOccupancy(new Vector3i(4, 0, 2)),
//			new BlockOccupancy(new Vector3i(5, 0, 2)),
//			new BlockOccupancy(new Vector3i(6, 0, 2)),
//			new BlockOccupancy(new Vector3i(7, 0, 2)),
			new BlockOccupancy(new Vector3i(8, 0, 2)),

			new BlockOccupancy(new Vector3i(0, 0, 3)),
//            new BlockOccupancy(new Vector3i(1, 0, 3)),
//            new BlockOccupancy(new Vector3i(2, 0, 3)),
//            new BlockOccupancy(new Vector3i(3, 0, 3)),
//            new BlockOccupancy(new Vector3i(4, 0, 3)),
//			new BlockOccupancy(new Vector3i(5, 0, 3)),
//			new BlockOccupancy(new Vector3i(6, 0, 3)),
//			new BlockOccupancy(new Vector3i(7, 0, 3)),
			new BlockOccupancy(new Vector3i(8, 0, 3)),

			new BlockOccupancy(new Vector3i(0, 0, 4)),
//            new BlockOccupancy(new Vector3i(1, 0, 4)),
//            new BlockOccupancy(new Vector3i(2, 0, 4)),
//            new BlockOccupancy(new Vector3i(3, 0, 4)),
//            new BlockOccupancy(new Vector3i(4, 0, 4)),
//			new BlockOccupancy(new Vector3i(5, 0, 4)),
//			new BlockOccupancy(new Vector3i(6, 0, 4)),
//			new BlockOccupancy(new Vector3i(7, 0, 4)),
			new BlockOccupancy(new Vector3i(8, 0, 4)),

			new BlockOccupancy(new Vector3i(0, 0, 5)),
//            new BlockOccupancy(new Vector3i(1, 0, 5)),
//            new BlockOccupancy(new Vector3i(2, 0, 5)),
//            new BlockOccupancy(new Vector3i(3, 0, 5)),
//            new BlockOccupancy(new Vector3i(4, 0, 5)),
//			new BlockOccupancy(new Vector3i(5, 0, 5)),
//			new BlockOccupancy(new Vector3i(6, 0, 5)),
//			new BlockOccupancy(new Vector3i(7, 0, 5)),
			new BlockOccupancy(new Vector3i(8, 0, 5)),

			new BlockOccupancy(new Vector3i(0, 0, 6)),
//            new BlockOccupancy(new Vector3i(1, 0, 6)),
//            new BlockOccupancy(new Vector3i(2, 0, 6)),
//            new BlockOccupancy(new Vector3i(3, 0, 6)),
//            new BlockOccupancy(new Vector3i(4, 0, 6)),
//			new BlockOccupancy(new Vector3i(5, 0, 6)),
//			new BlockOccupancy(new Vector3i(6, 0, 6)),
//			new BlockOccupancy(new Vector3i(7, 0, 6)),
			new BlockOccupancy(new Vector3i(8, 0, 6)),

			new BlockOccupancy(new Vector3i(0, 0, 7)),
//            new BlockOccupancy(new Vector3i(1, 0, 7)),
//            new BlockOccupancy(new Vector3i(2, 0, 7)),
//            new BlockOccupancy(new Vector3i(3, 0, 7)),
//            new BlockOccupancy(new Vector3i(4, 0, 7)),
//			new BlockOccupancy(new Vector3i(5, 0, 7)),
//			new BlockOccupancy(new Vector3i(6, 0, 7)),
//			new BlockOccupancy(new Vector3i(7, 0, 7)),
			new BlockOccupancy(new Vector3i(8, 0, 7)),

			new BlockOccupancy(new Vector3i(0, 0, 8)),
//            new BlockOccupancy(new Vector3i(1, 0, 8)),
//            new BlockOccupancy(new Vector3i(2, 0, 8)),
//            new BlockOccupancy(new Vector3i(3, 0, 8)),
//            new BlockOccupancy(new Vector3i(4, 0, 8)),
//			new BlockOccupancy(new Vector3i(5, 0, 8)),
//			new BlockOccupancy(new Vector3i(6, 0, 8)),
//			new BlockOccupancy(new Vector3i(7, 0, 8)),
			new BlockOccupancy(new Vector3i(8, 0, 8)),

			new BlockOccupancy(new Vector3i(0, 0, 9)),
//            new BlockOccupancy(new Vector3i(1, 0, 9)),
//            new BlockOccupancy(new Vector3i(2, 0, 9)),
//            new BlockOccupancy(new Vector3i(3, 0, 9)),
//            new BlockOccupancy(new Vector3i(4, 0, 9)),
//			new BlockOccupancy(new Vector3i(5, 0, 9)),
//			new BlockOccupancy(new Vector3i(6, 0, 9)),
//			new BlockOccupancy(new Vector3i(7, 0, 9)),
			new BlockOccupancy(new Vector3i(8, 0, 9)),

			new BlockOccupancy(new Vector3i(0, 0, 10)),
//            new BlockOccupancy(new Vector3i(1, 0, 10)),
//            new BlockOccupancy(new Vector3i(2, 0, 10)),
//            new BlockOccupancy(new Vector3i(3, 0, 10)),
//            new BlockOccupancy(new Vector3i(4, 0, 10)),
//			new BlockOccupancy(new Vector3i(5, 0, 10)),
//			new BlockOccupancy(new Vector3i(6, 0, 10)),
//			new BlockOccupancy(new Vector3i(7, 0, 10)),
			new BlockOccupancy(new Vector3i(8, 0, 10)),

			new BlockOccupancy(new Vector3i(0, 0, 11)),
//            new BlockOccupancy(new Vector3i(1, 0, 11)),
//            new BlockOccupancy(new Vector3i(2, 0, 11)),
//            new BlockOccupancy(new Vector3i(3, 0, 11)),
//            new BlockOccupancy(new Vector3i(4, 0, 11)),
//			new BlockOccupancy(new Vector3i(5, 0, 11)),
//			new BlockOccupancy(new Vector3i(6, 0, 11)),
//			new BlockOccupancy(new Vector3i(7, 0, 11)),
			new BlockOccupancy(new Vector3i(8, 0, 11)),

			new BlockOccupancy(new Vector3i(0, 0, 12)),
//            new BlockOccupancy(new Vector3i(1, 0, 12)),
//            new BlockOccupancy(new Vector3i(2, 0, 12)),
//            new BlockOccupancy(new Vector3i(3, 0, 12)),
//            new BlockOccupancy(new Vector3i(4, 0, 12)),
//			new BlockOccupancy(new Vector3i(5, 0, 12)),
//			new BlockOccupancy(new Vector3i(6, 0, 12)),
//			new BlockOccupancy(new Vector3i(7, 0, 12)),
			new BlockOccupancy(new Vector3i(8, 0, 12)),
			
			new BlockOccupancy(new Vector3i(0, 0, 13)),
            new BlockOccupancy(new Vector3i(1, 0, 13)),
            new BlockOccupancy(new Vector3i(2, 0, 13)),
            new BlockOccupancy(new Vector3i(3, 0, 13)),
            new BlockOccupancy(new Vector3i(4, 0, 13)),
			new BlockOccupancy(new Vector3i(5, 0, 13)),
			new BlockOccupancy(new Vector3i(6, 0, 13)),
			new BlockOccupancy(new Vector3i(7, 0, 13)),
			new BlockOccupancy(new Vector3i(8, 0, 13)),
			
//////////////////////////////////////5x4x13Back//////////////////////////////////////

			new BlockOccupancy(new Vector3i(0, 1, 0)),
            new BlockOccupancy(new Vector3i(1, 1, 0)),
            new BlockOccupancy(new Vector3i(2, 1, 0)),
            new BlockOccupancy(new Vector3i(3, 1, 0)),
            new BlockOccupancy(new Vector3i(4, 1, 0)),
			new BlockOccupancy(new Vector3i(5, 1, 0)),
			new BlockOccupancy(new Vector3i(6, 1, 0)),
			new BlockOccupancy(new Vector3i(7, 1, 0)),
			new BlockOccupancy(new Vector3i(8, 1, 0)),
		
            new BlockOccupancy(new Vector3i(0, 1, 1)),
//            new BlockOccupancy(new Vector3i(1, 1, 1)),
//            new BlockOccupancy(new Vector3i(2, 1, 1)),
//            new BlockOccupancy(new Vector3i(3, 1, 1)),
//            new BlockOccupancy(new Vector3i(4, 1, 1)),
//			new BlockOccupancy(new Vector3i(5, 1, 1)),
//			new BlockOccupancy(new Vector3i(6, 1, 1)),
//			new BlockOccupancy(new Vector3i(7, 1, 1)),
			new BlockOccupancy(new Vector3i(8, 1, 1)),
			

			new BlockOccupancy(new Vector3i(0, 1, 2)),
//            new BlockOccupancy(new Vector3i(1, 1, 2)),
//            new BlockOccupancy(new Vector3i(2, 1, 2)),
//            new BlockOccupancy(new Vector3i(3, 1, 2)),
//            new BlockOccupancy(new Vector3i(4, 1, 2)),
//			new BlockOccupancy(new Vector3i(5, 1, 2)),
//			new BlockOccupancy(new Vector3i(6, 1, 2)),
//			new BlockOccupancy(new Vector3i(7, 1, 2)),
			new BlockOccupancy(new Vector3i(8, 1, 2)),

			new BlockOccupancy(new Vector3i(0, 1, 3)),
//            new BlockOccupancy(new Vector3i(1, 1, 3)),
//            new BlockOccupancy(new Vector3i(2, 1, 3)),
//            new BlockOccupancy(new Vector3i(3, 1, 3)),
//            new BlockOccupancy(new Vector3i(4, 1, 3)),
//			new BlockOccupancy(new Vector3i(5, 1, 3)),
//			new BlockOccupancy(new Vector3i(6, 1, 3)),
//			new BlockOccupancy(new Vector3i(7, 1, 3)),
			new BlockOccupancy(new Vector3i(8, 1, 3)),

			new BlockOccupancy(new Vector3i(0, 1, 4)),
//            new BlockOccupancy(new Vector3i(1, 1, 4)),
//            new BlockOccupancy(new Vector3i(2, 1, 4)),
//            new BlockOccupancy(new Vector3i(3, 1, 4)),
//            new BlockOccupancy(new Vector3i(4, 1, 4)),
//			new BlockOccupancy(new Vector3i(5, 1, 4)),
//			new BlockOccupancy(new Vector3i(6, 1, 4)),
//			new BlockOccupancy(new Vector3i(7, 1, 4)),
			new BlockOccupancy(new Vector3i(8, 1, 4)),

			new BlockOccupancy(new Vector3i(0, 1, 5)),
//            new BlockOccupancy(new Vector3i(1, 1, 5)),
//            new BlockOccupancy(new Vector3i(2, 1, 5)),
//            new BlockOccupancy(new Vector3i(3, 1, 5)),
//            new BlockOccupancy(new Vector3i(4, 1, 5)),
//			new BlockOccupancy(new Vector3i(5, 1, 5)),
//			new BlockOccupancy(new Vector3i(6, 1, 5)),
//			new BlockOccupancy(new Vector3i(7, 1, 5)),
			new BlockOccupancy(new Vector3i(8, 1, 5)),

			new BlockOccupancy(new Vector3i(0, 1, 6)),
//            new BlockOccupancy(new Vector3i(1, 1, 6)),
//            new BlockOccupancy(new Vector3i(2, 1, 6)),
//            new BlockOccupancy(new Vector3i(3, 1, 6)),
//            new BlockOccupancy(new Vector3i(4, 1, 6)),
//			new BlockOccupancy(new Vector3i(5, 1, 6)),
//			new BlockOccupancy(new Vector3i(6, 1, 6)),
//			new BlockOccupancy(new Vector3i(7, 1, 6)),
			new BlockOccupancy(new Vector3i(8, 1, 6)),

			new BlockOccupancy(new Vector3i(0, 1, 7)),
//            new BlockOccupancy(new Vector3i(1, 1, 7)),
//            new BlockOccupancy(new Vector3i(2, 1, 7)),
//            new BlockOccupancy(new Vector3i(3, 1, 7)),
//            new BlockOccupancy(new Vector3i(4, 1, 7)),
//			new BlockOccupancy(new Vector3i(5, 1, 7)),
//			new BlockOccupancy(new Vector3i(6, 1, 7)),
//			new BlockOccupancy(new Vector3i(7, 1, 7)),
			new BlockOccupancy(new Vector3i(8, 1, 7)),

			new BlockOccupancy(new Vector3i(0, 1, 8)),
//            new BlockOccupancy(new Vector3i(1, 1, 8)),
//            new BlockOccupancy(new Vector3i(2, 1, 8)),
//            new BlockOccupancy(new Vector3i(3, 1, 8)),
//            new BlockOccupancy(new Vector3i(4, 1, 8)),
//			new BlockOccupancy(new Vector3i(5, 1, 8)),
//			new BlockOccupancy(new Vector3i(6, 1, 8)),
//			new BlockOccupancy(new Vector3i(7, 1, 8)),
			new BlockOccupancy(new Vector3i(8, 1, 8)),

			new BlockOccupancy(new Vector3i(0, 1, 9)),
//            new BlockOccupancy(new Vector3i(1, 1, 9)),
//            new BlockOccupancy(new Vector3i(2, 1, 9)),
//            new BlockOccupancy(new Vector3i(3, 1, 9)),
//            new BlockOccupancy(new Vector3i(4, 1, 9)),
//			new BlockOccupancy(new Vector3i(5, 1, 9)),
//			new BlockOccupancy(new Vector3i(6, 1, 9)),
//			new BlockOccupancy(new Vector3i(7, 1, 9)),
			new BlockOccupancy(new Vector3i(8, 1, 9)),

			new BlockOccupancy(new Vector3i(0, 1, 10)),
//            new BlockOccupancy(new Vector3i(1, 1, 10)),
//            new BlockOccupancy(new Vector3i(2, 1, 10)),
//            new BlockOccupancy(new Vector3i(3, 1, 10)),
//            new BlockOccupancy(new Vector3i(4, 1, 10)),
//			new BlockOccupancy(new Vector3i(5, 1, 10)),
//			new BlockOccupancy(new Vector3i(6, 1, 10)),
//			new BlockOccupancy(new Vector3i(7, 1, 10)),
			new BlockOccupancy(new Vector3i(8, 1, 10)),

			new BlockOccupancy(new Vector3i(0, 1, 11)),
//            new BlockOccupancy(new Vector3i(1, 1, 11)),
//            new BlockOccupancy(new Vector3i(2, 1, 11)),
//            new BlockOccupancy(new Vector3i(3, 1, 11)),
//            new BlockOccupancy(new Vector3i(4, 1, 11)),
//			new BlockOccupancy(new Vector3i(5, 1, 11)),
//			new BlockOccupancy(new Vector3i(6, 1, 11)),
//			new BlockOccupancy(new Vector3i(7, 1, 11)),
			new BlockOccupancy(new Vector3i(8, 1, 11)),

			new BlockOccupancy(new Vector3i(0, 1, 12)),
//            new BlockOccupancy(new Vector3i(1, 1, 12)),
//            new BlockOccupancy(new Vector3i(2, 1, 12)),
//            new BlockOccupancy(new Vector3i(3, 1, 12)),
//            new BlockOccupancy(new Vector3i(4, 1, 12)),
//			new BlockOccupancy(new Vector3i(5, 1, 12)),
//			new BlockOccupancy(new Vector3i(6, 1, 12)),
//			new BlockOccupancy(new Vector3i(7, 1, 12)),
			new BlockOccupancy(new Vector3i(8, 1, 12)),
			
			new BlockOccupancy(new Vector3i(0, 1, 13)),
            new BlockOccupancy(new Vector3i(1, 1, 13)),
            new BlockOccupancy(new Vector3i(2, 1, 13)),
            new BlockOccupancy(new Vector3i(3, 1, 13)),
            new BlockOccupancy(new Vector3i(4, 1, 13)),
			new BlockOccupancy(new Vector3i(5, 1, 13)),
			new BlockOccupancy(new Vector3i(6, 1, 13)),
			new BlockOccupancy(new Vector3i(7, 1, 13)),
			new BlockOccupancy(new Vector3i(8, 1, 13)),
			//////////////////////////////////////////////
			
			new BlockOccupancy(new Vector3i(0, 2, 0)),
            new BlockOccupancy(new Vector3i(1, 2, 0)),
            new BlockOccupancy(new Vector3i(2, 2, 0)),
            new BlockOccupancy(new Vector3i(3, 2, 0)),
            new BlockOccupancy(new Vector3i(4, 2, 0)),
			new BlockOccupancy(new Vector3i(5, 2, 0)),
			new BlockOccupancy(new Vector3i(6, 2, 0)),
			new BlockOccupancy(new Vector3i(7, 2, 0)),
			new BlockOccupancy(new Vector3i(8, 2, 0)),
		
            new BlockOccupancy(new Vector3i(0, 2, 1)),
//            new BlockOccupancy(new Vector3i(1, 2, 1)),
//            new BlockOccupancy(new Vector3i(2, 2, 1)),
//            new BlockOccupancy(new Vector3i(3, 2, 1)),
//            new BlockOccupancy(new Vector3i(4, 2, 1)),
//			new BlockOccupancy(new Vector3i(5, 2, 1)),
//			new BlockOccupancy(new Vector3i(6, 2, 1)),
//			new BlockOccupancy(new Vector3i(7, 2, 1)),
			new BlockOccupancy(new Vector3i(8, 2, 1)),
			

			new BlockOccupancy(new Vector3i(0, 2, 2)),
//            new BlockOccupancy(new Vector3i(1, 2, 2)),
//            new BlockOccupancy(new Vector3i(2, 2, 2)),
//            new BlockOccupancy(new Vector3i(3, 2, 2)),
//            new BlockOccupancy(new Vector3i(4, 2, 2)),
//			new BlockOccupancy(new Vector3i(5, 2, 2)),
//			new BlockOccupancy(new Vector3i(6, 2, 2)),
//			new BlockOccupancy(new Vector3i(7, 2, 2)),
			new BlockOccupancy(new Vector3i(8, 2, 2)),

			new BlockOccupancy(new Vector3i(0, 2, 3)),
//            new BlockOccupancy(new Vector3i(1, 2, 3)),
//            new BlockOccupancy(new Vector3i(2, 2, 3)),
//            new BlockOccupancy(new Vector3i(3, 2, 3)),
//            new BlockOccupancy(new Vector3i(4, 2, 3)),
//			new BlockOccupancy(new Vector3i(5, 2, 3)),
//			new BlockOccupancy(new Vector3i(6, 2, 3)),
//			new BlockOccupancy(new Vector3i(7, 2, 3)),
			new BlockOccupancy(new Vector3i(8, 2, 3)),

			new BlockOccupancy(new Vector3i(0, 2, 4)),
//            new BlockOccupancy(new Vector3i(1, 2, 4)),
//            new BlockOccupancy(new Vector3i(2, 2, 4)),
//            new BlockOccupancy(new Vector3i(3, 2, 4)),
//            new BlockOccupancy(new Vector3i(4, 2, 4)),
//			new BlockOccupancy(new Vector3i(5, 2, 4)),
//			new BlockOccupancy(new Vector3i(6, 2, 4)),
//			new BlockOccupancy(new Vector3i(7, 2, 4)),
			new BlockOccupancy(new Vector3i(8, 2, 4)),

			new BlockOccupancy(new Vector3i(0, 2, 5)),
//            new BlockOccupancy(new Vector3i(1, 2, 5)),
//            new BlockOccupancy(new Vector3i(2, 2, 5)),
//            new BlockOccupancy(new Vector3i(3, 2, 5)),
//            new BlockOccupancy(new Vector3i(4, 2, 5)),
//			new BlockOccupancy(new Vector3i(5, 2, 5)),
//			new BlockOccupancy(new Vector3i(6, 2, 5)),
//			new BlockOccupancy(new Vector3i(7, 2, 5)),
			new BlockOccupancy(new Vector3i(8, 2, 5)),

			new BlockOccupancy(new Vector3i(0, 2, 6)),
//            new BlockOccupancy(new Vector3i(1, 2, 6)),
//            new BlockOccupancy(new Vector3i(2, 2, 6)),
//            new BlockOccupancy(new Vector3i(3, 2, 6)),
//            new BlockOccupancy(new Vector3i(4, 2, 6)),
//			new BlockOccupancy(new Vector3i(5, 2, 6)),
//			new BlockOccupancy(new Vector3i(6, 2, 6)),
//			new BlockOccupancy(new Vector3i(7, 2, 6)),
			new BlockOccupancy(new Vector3i(8, 2, 6)),

			new BlockOccupancy(new Vector3i(0, 2, 7)),
//            new BlockOccupancy(new Vector3i(1, 2, 7)),
//            new BlockOccupancy(new Vector3i(2, 2, 7)),
//            new BlockOccupancy(new Vector3i(3, 2, 7)),
//            new BlockOccupancy(new Vector3i(4, 2, 7)),
//			new BlockOccupancy(new Vector3i(5, 2, 7)),
//			new BlockOccupancy(new Vector3i(6, 2, 7)),
//			new BlockOccupancy(new Vector3i(7, 2, 7)),
			new BlockOccupancy(new Vector3i(8, 2, 7)),

			new BlockOccupancy(new Vector3i(0, 2, 8)),
//            new BlockOccupancy(new Vector3i(1, 2, 8)),
//            new BlockOccupancy(new Vector3i(2, 2, 8)),
//            new BlockOccupancy(new Vector3i(3, 2, 8)),
//            new BlockOccupancy(new Vector3i(4, 2, 8)),
//			new BlockOccupancy(new Vector3i(5, 2, 8)),
//			new BlockOccupancy(new Vector3i(6, 2, 8)),
//			new BlockOccupancy(new Vector3i(7, 2, 8)),
			new BlockOccupancy(new Vector3i(8, 2, 8)),

			new BlockOccupancy(new Vector3i(0, 2, 9)),
//            new BlockOccupancy(new Vector3i(1, 2, 9)),
//            new BlockOccupancy(new Vector3i(2, 2, 9)),
//            new BlockOccupancy(new Vector3i(3, 2, 9)),
//            new BlockOccupancy(new Vector3i(4, 2, 9)),
//			new BlockOccupancy(new Vector3i(5, 2, 9)),
//			new BlockOccupancy(new Vector3i(6, 2, 9)),
//			new BlockOccupancy(new Vector3i(7, 2, 9)),
			new BlockOccupancy(new Vector3i(8, 2, 9)),

			new BlockOccupancy(new Vector3i(0, 2, 10)),
//            new BlockOccupancy(new Vector3i(1, 2, 10)),
//            new BlockOccupancy(new Vector3i(2, 2, 10)),
//            new BlockOccupancy(new Vector3i(3, 2, 10)),
//            new BlockOccupancy(new Vector3i(4, 2, 10)),
//			new BlockOccupancy(new Vector3i(5, 2, 10)),
//			new BlockOccupancy(new Vector3i(6, 2, 10)),
//			new BlockOccupancy(new Vector3i(7, 2, 10)),
			new BlockOccupancy(new Vector3i(8, 2, 10)),

			new BlockOccupancy(new Vector3i(0, 2, 11)),
//            new BlockOccupancy(new Vector3i(1, 2, 11)),
//            new BlockOccupancy(new Vector3i(2, 2, 11)),
//            new BlockOccupancy(new Vector3i(3, 2, 11)),
//            new BlockOccupancy(new Vector3i(4, 2, 11)),
//			new BlockOccupancy(new Vector3i(5, 2, 11)),
//			new BlockOccupancy(new Vector3i(6, 2, 11)),
//			new BlockOccupancy(new Vector3i(7, 2, 11)),
			new BlockOccupancy(new Vector3i(8, 2, 11)),

			new BlockOccupancy(new Vector3i(0, 2, 12)),
//            new BlockOccupancy(new Vector3i(1, 2, 12)),
//            new BlockOccupancy(new Vector3i(2, 2, 12)),
//            new BlockOccupancy(new Vector3i(3, 2, 12)),
//            new BlockOccupancy(new Vector3i(4, 2, 12)),
//			new BlockOccupancy(new Vector3i(5, 2, 12)),
//			new BlockOccupancy(new Vector3i(6, 2, 12)),
//			new BlockOccupancy(new Vector3i(7, 2, 12)),
			new BlockOccupancy(new Vector3i(8, 2, 12)),
			
			new BlockOccupancy(new Vector3i(0, 2, 13)),
            new BlockOccupancy(new Vector3i(1, 2, 13)),
            new BlockOccupancy(new Vector3i(2, 2, 13)),
            new BlockOccupancy(new Vector3i(3, 2, 13)),
            new BlockOccupancy(new Vector3i(4, 2, 13)),
			new BlockOccupancy(new Vector3i(5, 2, 13)),
			new BlockOccupancy(new Vector3i(6, 2, 13)),
			new BlockOccupancy(new Vector3i(7, 2, 13)),
			new BlockOccupancy(new Vector3i(8, 2, 13)),
			////////////////////////////////////////
			
			new BlockOccupancy(new Vector3i(0, 3, 0)),
            new BlockOccupancy(new Vector3i(1, 3, 0)),
            new BlockOccupancy(new Vector3i(2, 3, 0)),
            new BlockOccupancy(new Vector3i(3, 3, 0)),
            new BlockOccupancy(new Vector3i(4, 3, 0)),
			new BlockOccupancy(new Vector3i(5, 3, 0)),
			new BlockOccupancy(new Vector3i(6, 3, 0)),
			new BlockOccupancy(new Vector3i(7, 3, 0)),
			new BlockOccupancy(new Vector3i(8, 3, 0)),
		
            new BlockOccupancy(new Vector3i(0, 3, 1)),
            new BlockOccupancy(new Vector3i(1, 3, 1)),
            new BlockOccupancy(new Vector3i(2, 3, 1)),
            new BlockOccupancy(new Vector3i(3, 3, 1)),
            new BlockOccupancy(new Vector3i(4, 3, 1)),
			new BlockOccupancy(new Vector3i(5, 3, 1)),
			new BlockOccupancy(new Vector3i(6, 3, 1)),
			new BlockOccupancy(new Vector3i(7, 3, 1)),
			new BlockOccupancy(new Vector3i(8, 3, 1)),
			

			new BlockOccupancy(new Vector3i(0, 3, 2)),
            new BlockOccupancy(new Vector3i(1, 3, 2)),
            new BlockOccupancy(new Vector3i(2, 3, 2)),
            new BlockOccupancy(new Vector3i(3, 3, 2)),
            new BlockOccupancy(new Vector3i(4, 3, 2)),
			new BlockOccupancy(new Vector3i(5, 3, 2)),
			new BlockOccupancy(new Vector3i(6, 3, 2)),
			new BlockOccupancy(new Vector3i(7, 3, 2)),
			new BlockOccupancy(new Vector3i(8, 3, 2)),

			new BlockOccupancy(new Vector3i(0, 3, 3)),
            new BlockOccupancy(new Vector3i(1, 3, 3)),
            new BlockOccupancy(new Vector3i(2, 3, 3)),
            new BlockOccupancy(new Vector3i(3, 3, 3)),
            new BlockOccupancy(new Vector3i(4, 3, 3)),
			new BlockOccupancy(new Vector3i(5, 3, 3)),
			new BlockOccupancy(new Vector3i(6, 3, 3)),
			new BlockOccupancy(new Vector3i(7, 3, 3)),
			new BlockOccupancy(new Vector3i(8, 3, 3)),

			new BlockOccupancy(new Vector3i(0, 3, 4)),
            new BlockOccupancy(new Vector3i(1, 3, 4)),
            new BlockOccupancy(new Vector3i(2, 3, 4)),
            new BlockOccupancy(new Vector3i(3, 3, 4)),
            new BlockOccupancy(new Vector3i(4, 3, 4)),
			new BlockOccupancy(new Vector3i(5, 3, 4)),
			new BlockOccupancy(new Vector3i(6, 3, 4)),
			new BlockOccupancy(new Vector3i(7, 3, 4)),
			new BlockOccupancy(new Vector3i(8, 3, 4)),

			new BlockOccupancy(new Vector3i(0, 3, 5)),
            new BlockOccupancy(new Vector3i(1, 3, 5)),
            new BlockOccupancy(new Vector3i(2, 3, 5)),
            new BlockOccupancy(new Vector3i(3, 3, 5)),
            new BlockOccupancy(new Vector3i(4, 3, 5)),
			new BlockOccupancy(new Vector3i(5, 3, 5)),
			new BlockOccupancy(new Vector3i(6, 3, 5)),
			new BlockOccupancy(new Vector3i(7, 3, 5)),
			new BlockOccupancy(new Vector3i(8, 3, 5)),

			new BlockOccupancy(new Vector3i(0, 3, 6)),
            new BlockOccupancy(new Vector3i(1, 3, 6)),
            new BlockOccupancy(new Vector3i(2, 3, 6)),
            new BlockOccupancy(new Vector3i(3, 3, 6)),
            new BlockOccupancy(new Vector3i(4, 3, 6)),
			new BlockOccupancy(new Vector3i(5, 3, 6)),
			new BlockOccupancy(new Vector3i(6, 3, 6)),
			new BlockOccupancy(new Vector3i(7, 3, 6)),
			new BlockOccupancy(new Vector3i(8, 3, 6)),

			new BlockOccupancy(new Vector3i(0, 3, 7)),
            new BlockOccupancy(new Vector3i(1, 3, 7)),
            new BlockOccupancy(new Vector3i(2, 3, 7)),
            new BlockOccupancy(new Vector3i(3, 3, 7)),
            new BlockOccupancy(new Vector3i(4, 3, 7)),
			new BlockOccupancy(new Vector3i(5, 3, 7)),
			new BlockOccupancy(new Vector3i(6, 3, 7)),
			new BlockOccupancy(new Vector3i(7, 3, 7)),
			new BlockOccupancy(new Vector3i(8, 3, 7)),

			new BlockOccupancy(new Vector3i(0, 3, 8)),
            new BlockOccupancy(new Vector3i(1, 3, 8)),
            new BlockOccupancy(new Vector3i(2, 3, 8)),
            new BlockOccupancy(new Vector3i(3, 3, 8)),
            new BlockOccupancy(new Vector3i(4, 3, 8)),
			new BlockOccupancy(new Vector3i(5, 3, 8)),
			new BlockOccupancy(new Vector3i(6, 3, 8)),
			new BlockOccupancy(new Vector3i(7, 3, 8)),
			new BlockOccupancy(new Vector3i(8, 3, 8)),

			new BlockOccupancy(new Vector3i(0, 3, 9)),
            new BlockOccupancy(new Vector3i(1, 3, 9)),
            new BlockOccupancy(new Vector3i(2, 3, 9)),
            new BlockOccupancy(new Vector3i(3, 3, 9)),
            new BlockOccupancy(new Vector3i(4, 3, 9)),
			new BlockOccupancy(new Vector3i(5, 3, 9)),
			new BlockOccupancy(new Vector3i(6, 3, 9)),
			new BlockOccupancy(new Vector3i(7, 3, 9)),
			new BlockOccupancy(new Vector3i(8, 3, 9)),

			new BlockOccupancy(new Vector3i(0, 3, 10)),
            new BlockOccupancy(new Vector3i(1, 3, 10)),
            new BlockOccupancy(new Vector3i(2, 3, 10)),
            new BlockOccupancy(new Vector3i(3, 3, 10)),
            new BlockOccupancy(new Vector3i(4, 3, 10)),
			new BlockOccupancy(new Vector3i(5, 3, 10)),
			new BlockOccupancy(new Vector3i(6, 3, 10)),
			new BlockOccupancy(new Vector3i(7, 3, 10)),
			new BlockOccupancy(new Vector3i(8, 3, 10)),

			new BlockOccupancy(new Vector3i(0, 3, 11)),
            new BlockOccupancy(new Vector3i(1, 3, 11)),
            new BlockOccupancy(new Vector3i(2, 3, 11)),
            new BlockOccupancy(new Vector3i(3, 3, 11)),
            new BlockOccupancy(new Vector3i(4, 3, 11)),
			new BlockOccupancy(new Vector3i(5, 3, 11)),
			new BlockOccupancy(new Vector3i(6, 3, 11)),
			new BlockOccupancy(new Vector3i(7, 3, 11)),
			new BlockOccupancy(new Vector3i(8, 3, 11)),

			new BlockOccupancy(new Vector3i(0, 3, 12)),
            new BlockOccupancy(new Vector3i(1, 3, 12)),
            new BlockOccupancy(new Vector3i(2, 3, 12)),
            new BlockOccupancy(new Vector3i(3, 3, 12)),
            new BlockOccupancy(new Vector3i(4, 3, 12)),
			new BlockOccupancy(new Vector3i(5, 3, 12)),
			new BlockOccupancy(new Vector3i(6, 3, 12)),
			new BlockOccupancy(new Vector3i(7, 3, 12)),
			new BlockOccupancy(new Vector3i(8, 3, 12)),
			
			new BlockOccupancy(new Vector3i(0, 3, 13)),
            new BlockOccupancy(new Vector3i(1, 3, 13)),
            new BlockOccupancy(new Vector3i(2, 3, 13)),
            new BlockOccupancy(new Vector3i(3, 3, 13)),
            new BlockOccupancy(new Vector3i(4, 3, 13)),
			new BlockOccupancy(new Vector3i(5, 3, 13)),
			new BlockOccupancy(new Vector3i(6, 3, 13)),
			new BlockOccupancy(new Vector3i(7, 3, 13)),
			new BlockOccupancy(new Vector3i(8, 3, 13)),
			//////////////////////////////////////////
			
			new BlockOccupancy(new Vector3i(0, 4, 0)),
            new BlockOccupancy(new Vector3i(1, 4, 0)),
            new BlockOccupancy(new Vector3i(2, 4, 0)),
            new BlockOccupancy(new Vector3i(3, 4, 0)),
            new BlockOccupancy(new Vector3i(4, 4, 0)),
			new BlockOccupancy(new Vector3i(5, 4, 0)),
			new BlockOccupancy(new Vector3i(6, 4, 0)),
			new BlockOccupancy(new Vector3i(7, 4, 0)),
			new BlockOccupancy(new Vector3i(8, 4, 0)),
		
            new BlockOccupancy(new Vector3i(0, 4, 1)),
            new BlockOccupancy(new Vector3i(1, 4, 1)),
            new BlockOccupancy(new Vector3i(2, 4, 1)),
            new BlockOccupancy(new Vector3i(3, 4, 1)),
            new BlockOccupancy(new Vector3i(4, 4, 1)),
			new BlockOccupancy(new Vector3i(5, 4, 1)),
			new BlockOccupancy(new Vector3i(6, 4, 1)),
			new BlockOccupancy(new Vector3i(7, 4, 1)),
			new BlockOccupancy(new Vector3i(8, 4, 1)),
			

			new BlockOccupancy(new Vector3i(0, 4, 2)),
            new BlockOccupancy(new Vector3i(1, 4, 2)),
            new BlockOccupancy(new Vector3i(2, 4, 2)),
            new BlockOccupancy(new Vector3i(3, 4, 2)),
            new BlockOccupancy(new Vector3i(4, 4, 2)),
			new BlockOccupancy(new Vector3i(5, 4, 2)),
			new BlockOccupancy(new Vector3i(6, 4, 2)),
			new BlockOccupancy(new Vector3i(7, 4, 2)),
			new BlockOccupancy(new Vector3i(8, 4, 2)),

			new BlockOccupancy(new Vector3i(0, 4, 3)),
            new BlockOccupancy(new Vector3i(1, 4, 3)),
            new BlockOccupancy(new Vector3i(2, 4, 3)),
            new BlockOccupancy(new Vector3i(3, 4, 3)),
            new BlockOccupancy(new Vector3i(4, 4, 3)),
			new BlockOccupancy(new Vector3i(5, 4, 3)),
			new BlockOccupancy(new Vector3i(6, 4, 3)),
			new BlockOccupancy(new Vector3i(7, 4, 3)),
			new BlockOccupancy(new Vector3i(8, 4, 3)),

			new BlockOccupancy(new Vector3i(0, 4, 4)),
            new BlockOccupancy(new Vector3i(1, 4, 4)),
            new BlockOccupancy(new Vector3i(2, 4, 4)),
            new BlockOccupancy(new Vector3i(3, 4, 4)),
            new BlockOccupancy(new Vector3i(4, 4, 4)),
			new BlockOccupancy(new Vector3i(5, 4, 4)),
			new BlockOccupancy(new Vector3i(6, 4, 4)),
			new BlockOccupancy(new Vector3i(7, 4, 4)),
			new BlockOccupancy(new Vector3i(8, 4, 4)),

			new BlockOccupancy(new Vector3i(0, 4, 5)),
            new BlockOccupancy(new Vector3i(1, 4, 5)),
            new BlockOccupancy(new Vector3i(2, 4, 5)),
            new BlockOccupancy(new Vector3i(3, 4, 5)),
            new BlockOccupancy(new Vector3i(4, 4, 5)),
			new BlockOccupancy(new Vector3i(5, 4, 5)),
			new BlockOccupancy(new Vector3i(6, 4, 5)),
			new BlockOccupancy(new Vector3i(7, 4, 5)),
			new BlockOccupancy(new Vector3i(8, 4, 5)),

			new BlockOccupancy(new Vector3i(0, 4, 6)),
            new BlockOccupancy(new Vector3i(1, 4, 6)),
            new BlockOccupancy(new Vector3i(2, 4, 6)),
            new BlockOccupancy(new Vector3i(3, 4, 6)),
            new BlockOccupancy(new Vector3i(4, 4, 6)),
			new BlockOccupancy(new Vector3i(5, 4, 6)),
			new BlockOccupancy(new Vector3i(6, 4, 6)),
			new BlockOccupancy(new Vector3i(7, 4, 6)),
			new BlockOccupancy(new Vector3i(8, 4, 6)),

			new BlockOccupancy(new Vector3i(0, 4, 7)),
            new BlockOccupancy(new Vector3i(1, 4, 7)),
            new BlockOccupancy(new Vector3i(2, 4, 7)),
            new BlockOccupancy(new Vector3i(3, 4, 7)),
            new BlockOccupancy(new Vector3i(4, 4, 7)),
			new BlockOccupancy(new Vector3i(5, 4, 7)),
			new BlockOccupancy(new Vector3i(6, 4, 7)),
			new BlockOccupancy(new Vector3i(7, 4, 7)),
			new BlockOccupancy(new Vector3i(8, 4, 7)),

			new BlockOccupancy(new Vector3i(0, 4, 8)),
            new BlockOccupancy(new Vector3i(1, 4, 8)),
            new BlockOccupancy(new Vector3i(2, 4, 8)),
            new BlockOccupancy(new Vector3i(3, 4, 8)),
            new BlockOccupancy(new Vector3i(4, 4, 8)),
			new BlockOccupancy(new Vector3i(5, 4, 8)),
			new BlockOccupancy(new Vector3i(6, 4, 8)),
			new BlockOccupancy(new Vector3i(7, 4, 8)),
			new BlockOccupancy(new Vector3i(8, 4, 8)),

			new BlockOccupancy(new Vector3i(0, 4, 9)),
            new BlockOccupancy(new Vector3i(1, 4, 9)),
            new BlockOccupancy(new Vector3i(2, 4, 9)),
            new BlockOccupancy(new Vector3i(3, 4, 9)),
            new BlockOccupancy(new Vector3i(4, 4, 9)),
			new BlockOccupancy(new Vector3i(5, 4, 9)),
			new BlockOccupancy(new Vector3i(6, 4, 9)),
			new BlockOccupancy(new Vector3i(7, 4, 9)),
			new BlockOccupancy(new Vector3i(8, 4, 9)),

			new BlockOccupancy(new Vector3i(0, 4, 10)),
            new BlockOccupancy(new Vector3i(1, 4, 10)),
            new BlockOccupancy(new Vector3i(2, 4, 10)),
            new BlockOccupancy(new Vector3i(3, 4, 10)),
            new BlockOccupancy(new Vector3i(4, 4, 10)),
			new BlockOccupancy(new Vector3i(5, 4, 10)),
			new BlockOccupancy(new Vector3i(6, 4, 10)),
			new BlockOccupancy(new Vector3i(7, 4, 10)),
			new BlockOccupancy(new Vector3i(8, 4, 10)),

			new BlockOccupancy(new Vector3i(0, 4, 11)),
            new BlockOccupancy(new Vector3i(1, 4, 11)),
            new BlockOccupancy(new Vector3i(2, 4, 11)),
            new BlockOccupancy(new Vector3i(3, 4, 11)),
            new BlockOccupancy(new Vector3i(4, 4, 11)),
			new BlockOccupancy(new Vector3i(5, 4, 11)),
			new BlockOccupancy(new Vector3i(6, 4, 11)),
			new BlockOccupancy(new Vector3i(7, 4, 11)),
			new BlockOccupancy(new Vector3i(8, 4, 11)),

			new BlockOccupancy(new Vector3i(0, 4, 12)),
            new BlockOccupancy(new Vector3i(1, 4, 12)),
            new BlockOccupancy(new Vector3i(2, 4, 12)),
            new BlockOccupancy(new Vector3i(3, 4, 12)),
            new BlockOccupancy(new Vector3i(4, 4, 12)),
			new BlockOccupancy(new Vector3i(5, 4, 12)),
			new BlockOccupancy(new Vector3i(6, 4, 12)),
			new BlockOccupancy(new Vector3i(7, 4, 12)),
			new BlockOccupancy(new Vector3i(8, 4, 12)),
			
			new BlockOccupancy(new Vector3i(0, 4, 13)),
            new BlockOccupancy(new Vector3i(1, 4, 13)),
            new BlockOccupancy(new Vector3i(2, 4, 13)),
            new BlockOccupancy(new Vector3i(3, 4, 13)),
            new BlockOccupancy(new Vector3i(4, 4, 13)),
			new BlockOccupancy(new Vector3i(5, 4, 13)),
			new BlockOccupancy(new Vector3i(6, 4, 13)),
			new BlockOccupancy(new Vector3i(7, 4, 13)),
			new BlockOccupancy(new Vector3i(8, 4, 13)),
			/////////////////////////////////////////////
			
			new BlockOccupancy(new Vector3i(0, 5, 0)),
            new BlockOccupancy(new Vector3i(1, 5, 0)),
            new BlockOccupancy(new Vector3i(2, 5, 0)),
            new BlockOccupancy(new Vector3i(3, 5, 0)),
            new BlockOccupancy(new Vector3i(4, 5, 0)),
			new BlockOccupancy(new Vector3i(5, 5, 0)),
			new BlockOccupancy(new Vector3i(6, 5, 0)),
			new BlockOccupancy(new Vector3i(7, 5, 0)),
			new BlockOccupancy(new Vector3i(8, 5, 0)),
		
            new BlockOccupancy(new Vector3i(0, 5, 1)),
            new BlockOccupancy(new Vector3i(1, 5, 1)),
            new BlockOccupancy(new Vector3i(2, 5, 1)),
            new BlockOccupancy(new Vector3i(3, 5, 1)),
            new BlockOccupancy(new Vector3i(4, 5, 1)),
			new BlockOccupancy(new Vector3i(5, 5, 1)),
			new BlockOccupancy(new Vector3i(6, 5, 1)),
			new BlockOccupancy(new Vector3i(7, 5, 1)),
			new BlockOccupancy(new Vector3i(8, 5, 1)),
			

			new BlockOccupancy(new Vector3i(0, 5, 2)),
            new BlockOccupancy(new Vector3i(1, 5, 2)),
            new BlockOccupancy(new Vector3i(2, 5, 2)),
            new BlockOccupancy(new Vector3i(3, 5, 2)),
            new BlockOccupancy(new Vector3i(4, 5, 2)),
			new BlockOccupancy(new Vector3i(5, 5, 2)),
			new BlockOccupancy(new Vector3i(6, 5, 2)),
			new BlockOccupancy(new Vector3i(7, 5, 2)),
			new BlockOccupancy(new Vector3i(8, 5, 2)),

			new BlockOccupancy(new Vector3i(0, 5, 3)),
            new BlockOccupancy(new Vector3i(1, 5, 3)),
            new BlockOccupancy(new Vector3i(2, 5, 3)),
            new BlockOccupancy(new Vector3i(3, 5, 3)),
            new BlockOccupancy(new Vector3i(4, 5, 3)),
			new BlockOccupancy(new Vector3i(5, 5, 3)),
			new BlockOccupancy(new Vector3i(6, 5, 3)),
			new BlockOccupancy(new Vector3i(7, 5, 3)),
			new BlockOccupancy(new Vector3i(8, 5, 3)),

			new BlockOccupancy(new Vector3i(0, 5, 4)),
            new BlockOccupancy(new Vector3i(1, 5, 4)),
            new BlockOccupancy(new Vector3i(2, 5, 4)),
            new BlockOccupancy(new Vector3i(3, 5, 4)),
            new BlockOccupancy(new Vector3i(4, 5, 4)),
			new BlockOccupancy(new Vector3i(5, 5, 4)),
			new BlockOccupancy(new Vector3i(6, 5, 4)),
			new BlockOccupancy(new Vector3i(7, 5, 4)),
			new BlockOccupancy(new Vector3i(8, 5, 4)),

			new BlockOccupancy(new Vector3i(0, 5, 5)),
            new BlockOccupancy(new Vector3i(1, 5, 5)),
            new BlockOccupancy(new Vector3i(2, 5, 5)),
            new BlockOccupancy(new Vector3i(3, 5, 5)),
            new BlockOccupancy(new Vector3i(4, 5, 5)),
			new BlockOccupancy(new Vector3i(5, 5, 5)),
			new BlockOccupancy(new Vector3i(6, 5, 5)),
			new BlockOccupancy(new Vector3i(7, 5, 5)),
			new BlockOccupancy(new Vector3i(8, 5, 5)),

			new BlockOccupancy(new Vector3i(0, 5, 6)),
            new BlockOccupancy(new Vector3i(1, 5, 6)),
            new BlockOccupancy(new Vector3i(2, 5, 6)),
            new BlockOccupancy(new Vector3i(3, 5, 6)),
            new BlockOccupancy(new Vector3i(4, 5, 6)),
			new BlockOccupancy(new Vector3i(5, 5, 6)),
			new BlockOccupancy(new Vector3i(6, 5, 6)),
			new BlockOccupancy(new Vector3i(7, 5, 6)),
			new BlockOccupancy(new Vector3i(8, 5, 6)),

			new BlockOccupancy(new Vector3i(0, 5, 7)),
            new BlockOccupancy(new Vector3i(1, 5, 7)),
            new BlockOccupancy(new Vector3i(2, 5, 7)),
            new BlockOccupancy(new Vector3i(3, 5, 7)),
            new BlockOccupancy(new Vector3i(4, 5, 7)),
			new BlockOccupancy(new Vector3i(5, 5, 7)),
			new BlockOccupancy(new Vector3i(6, 5, 7)),
			new BlockOccupancy(new Vector3i(7, 5, 7)),
			new BlockOccupancy(new Vector3i(8, 5, 7)),

			new BlockOccupancy(new Vector3i(0, 5, 8)),
            new BlockOccupancy(new Vector3i(1, 5, 8)),
            new BlockOccupancy(new Vector3i(2, 5, 8)),
            new BlockOccupancy(new Vector3i(3, 5, 8)),
            new BlockOccupancy(new Vector3i(4, 5, 8)),
			new BlockOccupancy(new Vector3i(5, 5, 8)),
			new BlockOccupancy(new Vector3i(6, 5, 8)),
			new BlockOccupancy(new Vector3i(7, 5, 8)),
			new BlockOccupancy(new Vector3i(8, 5, 8)),

			new BlockOccupancy(new Vector3i(0, 5, 9)),
            new BlockOccupancy(new Vector3i(1, 5, 9)),
            new BlockOccupancy(new Vector3i(2, 5, 9)),
            new BlockOccupancy(new Vector3i(3, 5, 9)),
            new BlockOccupancy(new Vector3i(4, 5, 9)),
			new BlockOccupancy(new Vector3i(5, 5, 9)),
			new BlockOccupancy(new Vector3i(6, 5, 9)),
			new BlockOccupancy(new Vector3i(7, 5, 9)),
			new BlockOccupancy(new Vector3i(8, 5, 9)),

			new BlockOccupancy(new Vector3i(0, 5, 10)),
            new BlockOccupancy(new Vector3i(1, 5, 10)),
            new BlockOccupancy(new Vector3i(2, 5, 10)),
            new BlockOccupancy(new Vector3i(3, 5, 10)),
            new BlockOccupancy(new Vector3i(4, 5, 10)),
			new BlockOccupancy(new Vector3i(5, 5, 10)),
			new BlockOccupancy(new Vector3i(6, 5, 10)),
			new BlockOccupancy(new Vector3i(7, 5, 10)),
			new BlockOccupancy(new Vector3i(8, 5, 10)),

			new BlockOccupancy(new Vector3i(0, 5, 11)),
            new BlockOccupancy(new Vector3i(1, 5, 11)),
            new BlockOccupancy(new Vector3i(2, 5, 11)),
            new BlockOccupancy(new Vector3i(3, 5, 11)),
            new BlockOccupancy(new Vector3i(4, 5, 11)),
			new BlockOccupancy(new Vector3i(5, 5, 11)),
			new BlockOccupancy(new Vector3i(6, 5, 11)),
			new BlockOccupancy(new Vector3i(7, 5, 11)),
			new BlockOccupancy(new Vector3i(8, 5, 11)),

			new BlockOccupancy(new Vector3i(0, 5, 12)),
            new BlockOccupancy(new Vector3i(1, 5, 12)),
            new BlockOccupancy(new Vector3i(2, 5, 12)),
            new BlockOccupancy(new Vector3i(3, 5, 12)),
            new BlockOccupancy(new Vector3i(4, 5, 12)),
			new BlockOccupancy(new Vector3i(5, 5, 12)),
			new BlockOccupancy(new Vector3i(6, 5, 12)),
			new BlockOccupancy(new Vector3i(7, 5, 12)),
			new BlockOccupancy(new Vector3i(8, 5, 12)),
			
			new BlockOccupancy(new Vector3i(0, 5, 13)),
            new BlockOccupancy(new Vector3i(1, 5, 13)),
            new BlockOccupancy(new Vector3i(2, 5, 13)),
            new BlockOccupancy(new Vector3i(3, 5, 13)),
            new BlockOccupancy(new Vector3i(4, 5, 13)),
			new BlockOccupancy(new Vector3i(5, 5, 13)),
			new BlockOccupancy(new Vector3i(6, 5, 13)),
			new BlockOccupancy(new Vector3i(7, 5, 13)),
			new BlockOccupancy(new Vector3i(8, 5, 13)),
			/////////////////////////////////////////////
			
			new BlockOccupancy(new Vector3i(0, 6, 0)),
            new BlockOccupancy(new Vector3i(1, 6, 0)),
            new BlockOccupancy(new Vector3i(2, 6, 0)),
            new BlockOccupancy(new Vector3i(3, 6, 0)),
            new BlockOccupancy(new Vector3i(4, 6, 0)),
			new BlockOccupancy(new Vector3i(5, 6, 0)),
			new BlockOccupancy(new Vector3i(6, 6, 0)),
			new BlockOccupancy(new Vector3i(7, 6, 0)),
			new BlockOccupancy(new Vector3i(8, 6, 0)),
		
            new BlockOccupancy(new Vector3i(0, 6, 1)),
            new BlockOccupancy(new Vector3i(1, 6, 1)),
            new BlockOccupancy(new Vector3i(2, 6, 1)),
            new BlockOccupancy(new Vector3i(3, 6, 1)),
            new BlockOccupancy(new Vector3i(4, 6, 1)),
			new BlockOccupancy(new Vector3i(5, 6, 1)),
			new BlockOccupancy(new Vector3i(6, 6, 1)),
			new BlockOccupancy(new Vector3i(7, 6, 1)),
			new BlockOccupancy(new Vector3i(8, 6, 1)),
			

			new BlockOccupancy(new Vector3i(0, 6, 2)),
            new BlockOccupancy(new Vector3i(1, 6, 2)),
            new BlockOccupancy(new Vector3i(2, 6, 2)),
            new BlockOccupancy(new Vector3i(3, 6, 2)),
            new BlockOccupancy(new Vector3i(4, 6, 2)),
			new BlockOccupancy(new Vector3i(5, 6, 2)),
			new BlockOccupancy(new Vector3i(6, 6, 2)),
			new BlockOccupancy(new Vector3i(7, 6, 2)),
			new BlockOccupancy(new Vector3i(8, 6, 2)),

			new BlockOccupancy(new Vector3i(0, 6, 3)),
            new BlockOccupancy(new Vector3i(1, 6, 3)),
            new BlockOccupancy(new Vector3i(2, 6, 3)),
            new BlockOccupancy(new Vector3i(3, 6, 3)),
            new BlockOccupancy(new Vector3i(4, 6, 3)),
			new BlockOccupancy(new Vector3i(5, 6, 3)),
			new BlockOccupancy(new Vector3i(6, 6, 3)),
			new BlockOccupancy(new Vector3i(7, 6, 3)),
			new BlockOccupancy(new Vector3i(8, 6, 3)),

			new BlockOccupancy(new Vector3i(0, 6, 4)),
            new BlockOccupancy(new Vector3i(1, 6, 4)),
            new BlockOccupancy(new Vector3i(2, 6, 4)),
            new BlockOccupancy(new Vector3i(3, 6, 4)),
            new BlockOccupancy(new Vector3i(4, 6, 4)),
			new BlockOccupancy(new Vector3i(5, 6, 4)),
			new BlockOccupancy(new Vector3i(6, 6, 4)),
			new BlockOccupancy(new Vector3i(7, 6, 4)),
			new BlockOccupancy(new Vector3i(8, 6, 4)),

			new BlockOccupancy(new Vector3i(0, 6, 5)),
            new BlockOccupancy(new Vector3i(1, 6, 5)),
            new BlockOccupancy(new Vector3i(2, 6, 5)),
            new BlockOccupancy(new Vector3i(3, 6, 5)),
            new BlockOccupancy(new Vector3i(4, 6, 5)),
			new BlockOccupancy(new Vector3i(5, 6, 5)),
			new BlockOccupancy(new Vector3i(6, 6, 5)),
			new BlockOccupancy(new Vector3i(7, 6, 5)),
			new BlockOccupancy(new Vector3i(8, 6, 5)),

			new BlockOccupancy(new Vector3i(0, 6, 6)),
            new BlockOccupancy(new Vector3i(1, 6, 6)),
            new BlockOccupancy(new Vector3i(2, 6, 6)),
            new BlockOccupancy(new Vector3i(3, 6, 6)),
            new BlockOccupancy(new Vector3i(4, 6, 6)),
			new BlockOccupancy(new Vector3i(5, 6, 6)),
			new BlockOccupancy(new Vector3i(6, 6, 6)),
			new BlockOccupancy(new Vector3i(7, 6, 6)),
			new BlockOccupancy(new Vector3i(8, 6, 6)),

			new BlockOccupancy(new Vector3i(0, 6, 7)),
            new BlockOccupancy(new Vector3i(1, 6, 7)),
            new BlockOccupancy(new Vector3i(2, 6, 7)),
            new BlockOccupancy(new Vector3i(3, 6, 7)),
            new BlockOccupancy(new Vector3i(4, 6, 7)),
			new BlockOccupancy(new Vector3i(5, 6, 7)),
			new BlockOccupancy(new Vector3i(6, 6, 7)),
			new BlockOccupancy(new Vector3i(7, 6, 7)),
			new BlockOccupancy(new Vector3i(8, 6, 7)),

			new BlockOccupancy(new Vector3i(0, 6, 8)),
            new BlockOccupancy(new Vector3i(1, 6, 8)),
            new BlockOccupancy(new Vector3i(2, 6, 8)),
            new BlockOccupancy(new Vector3i(3, 6, 8)),
            new BlockOccupancy(new Vector3i(4, 6, 8)),
			new BlockOccupancy(new Vector3i(5, 6, 8)),
			new BlockOccupancy(new Vector3i(6, 6, 8)),
			new BlockOccupancy(new Vector3i(7, 6, 8)),
			new BlockOccupancy(new Vector3i(8, 6, 8)),

			new BlockOccupancy(new Vector3i(0, 6, 9)),
            new BlockOccupancy(new Vector3i(1, 6, 9)),
            new BlockOccupancy(new Vector3i(2, 6, 9)),
            new BlockOccupancy(new Vector3i(3, 6, 9)),
            new BlockOccupancy(new Vector3i(4, 6, 9)),
			new BlockOccupancy(new Vector3i(5, 6, 9)),
			new BlockOccupancy(new Vector3i(6, 6, 9)),
			new BlockOccupancy(new Vector3i(7, 6, 9)),
			new BlockOccupancy(new Vector3i(8, 6, 9)),

			new BlockOccupancy(new Vector3i(0, 6, 10)),
            new BlockOccupancy(new Vector3i(1, 6, 10)),
            new BlockOccupancy(new Vector3i(2, 6, 10)),
            new BlockOccupancy(new Vector3i(3, 6, 10)),
            new BlockOccupancy(new Vector3i(4, 6, 10)),
			new BlockOccupancy(new Vector3i(5, 6, 10)),
			new BlockOccupancy(new Vector3i(6, 6, 10)),
			new BlockOccupancy(new Vector3i(7, 6, 10)),
			new BlockOccupancy(new Vector3i(8, 6, 10)),

			new BlockOccupancy(new Vector3i(0, 6, 11)),
            new BlockOccupancy(new Vector3i(1, 6, 11)),
            new BlockOccupancy(new Vector3i(2, 6, 11)),
            new BlockOccupancy(new Vector3i(3, 6, 11)),
            new BlockOccupancy(new Vector3i(4, 6, 11)),
			new BlockOccupancy(new Vector3i(5, 6, 11)),
			new BlockOccupancy(new Vector3i(6, 6, 11)),
			new BlockOccupancy(new Vector3i(7, 6, 11)),
			new BlockOccupancy(new Vector3i(8, 6, 11)),

			new BlockOccupancy(new Vector3i(0, 6, 12)),
            new BlockOccupancy(new Vector3i(1, 6, 12)),
            new BlockOccupancy(new Vector3i(2, 6, 12)),
            new BlockOccupancy(new Vector3i(3, 6, 12)),
            new BlockOccupancy(new Vector3i(4, 6, 12)),
			new BlockOccupancy(new Vector3i(5, 6, 12)),
			new BlockOccupancy(new Vector3i(6, 6, 12)),
			new BlockOccupancy(new Vector3i(7, 6, 12)),
			new BlockOccupancy(new Vector3i(8, 6, 12)),
			
			new BlockOccupancy(new Vector3i(0, 6, 13)),
            new BlockOccupancy(new Vector3i(1, 6, 13)),
            new BlockOccupancy(new Vector3i(2, 6, 13)),
            new BlockOccupancy(new Vector3i(3, 6, 13)),
            new BlockOccupancy(new Vector3i(4, 6, 13)),
			new BlockOccupancy(new Vector3i(5, 6, 13)),
			new BlockOccupancy(new Vector3i(6, 6, 13)),
			new BlockOccupancy(new Vector3i(7, 6, 13)),
			new BlockOccupancy(new Vector3i(8, 6, 13)),
			///////////////////////////////////////////
			
			new BlockOccupancy(new Vector3i(0, 7, 0)),
            new BlockOccupancy(new Vector3i(1, 7, 0)),
            new BlockOccupancy(new Vector3i(2, 7, 0)),
            new BlockOccupancy(new Vector3i(3, 7, 0)),
            new BlockOccupancy(new Vector3i(4, 7, 0)),
			new BlockOccupancy(new Vector3i(5, 7, 0)),
			new BlockOccupancy(new Vector3i(6, 7, 0)),
			new BlockOccupancy(new Vector3i(7, 7, 0)),
			new BlockOccupancy(new Vector3i(8, 7, 0)),
		
            new BlockOccupancy(new Vector3i(0, 7, 1)),
            new BlockOccupancy(new Vector3i(1, 7, 1)),
            new BlockOccupancy(new Vector3i(2, 7, 1)),
            new BlockOccupancy(new Vector3i(3, 7, 1)),
            new BlockOccupancy(new Vector3i(4, 7, 1)),
			new BlockOccupancy(new Vector3i(5, 7, 1)),
			new BlockOccupancy(new Vector3i(6, 7, 1)),
			new BlockOccupancy(new Vector3i(7, 7, 1)),
			new BlockOccupancy(new Vector3i(8, 7, 1)),
			

			new BlockOccupancy(new Vector3i(0, 7, 2)),
            new BlockOccupancy(new Vector3i(1, 7, 2)),
            new BlockOccupancy(new Vector3i(2, 7, 2)),
            new BlockOccupancy(new Vector3i(3, 7, 2)),
            new BlockOccupancy(new Vector3i(4, 7, 2)),
			new BlockOccupancy(new Vector3i(5, 7, 2)),
			new BlockOccupancy(new Vector3i(6, 7, 2)),
			new BlockOccupancy(new Vector3i(7, 7, 2)),
			new BlockOccupancy(new Vector3i(8, 7, 2)),

			new BlockOccupancy(new Vector3i(0, 7, 3)),
            new BlockOccupancy(new Vector3i(1, 7, 3)),
            new BlockOccupancy(new Vector3i(2, 7, 3)),
            new BlockOccupancy(new Vector3i(3, 7, 3)),
            new BlockOccupancy(new Vector3i(4, 7, 3)),
			new BlockOccupancy(new Vector3i(5, 7, 3)),
			new BlockOccupancy(new Vector3i(6, 7, 3)),
			new BlockOccupancy(new Vector3i(7, 7, 3)),
			new BlockOccupancy(new Vector3i(8, 7, 3)),

			new BlockOccupancy(new Vector3i(0, 7, 4)),
            new BlockOccupancy(new Vector3i(1, 7, 4)),
            new BlockOccupancy(new Vector3i(2, 7, 4)),
            new BlockOccupancy(new Vector3i(3, 7, 4)),
            new BlockOccupancy(new Vector3i(4, 7, 4)),
			new BlockOccupancy(new Vector3i(5, 7, 4)),
			new BlockOccupancy(new Vector3i(6, 7, 4)),
			new BlockOccupancy(new Vector3i(7, 7, 4)),
			new BlockOccupancy(new Vector3i(8, 7, 4)),

			new BlockOccupancy(new Vector3i(0, 7, 5)),
            new BlockOccupancy(new Vector3i(1, 7, 5)),
            new BlockOccupancy(new Vector3i(2, 7, 5)),
            new BlockOccupancy(new Vector3i(3, 7, 5)),
            new BlockOccupancy(new Vector3i(4, 7, 5)),
			new BlockOccupancy(new Vector3i(5, 7, 5)),
			new BlockOccupancy(new Vector3i(6, 7, 5)),
			new BlockOccupancy(new Vector3i(7, 7, 5)),
			new BlockOccupancy(new Vector3i(8, 7, 5)),

			new BlockOccupancy(new Vector3i(0, 7, 6)),
            new BlockOccupancy(new Vector3i(1, 7, 6)),
            new BlockOccupancy(new Vector3i(2, 7, 6)),
            new BlockOccupancy(new Vector3i(3, 7, 6)),
            new BlockOccupancy(new Vector3i(4, 7, 6)),
			new BlockOccupancy(new Vector3i(5, 7, 6)),
			new BlockOccupancy(new Vector3i(6, 7, 6)),
			new BlockOccupancy(new Vector3i(7, 7, 6)),
			new BlockOccupancy(new Vector3i(8, 7, 6)),

			new BlockOccupancy(new Vector3i(0, 7, 7)),
            new BlockOccupancy(new Vector3i(1, 7, 7)),
            new BlockOccupancy(new Vector3i(2, 7, 7)),
            new BlockOccupancy(new Vector3i(3, 7, 7)),
            new BlockOccupancy(new Vector3i(4, 7, 7)),
			new BlockOccupancy(new Vector3i(5, 7, 7)),
			new BlockOccupancy(new Vector3i(6, 7, 7)),
			new BlockOccupancy(new Vector3i(7, 7, 7)),
			new BlockOccupancy(new Vector3i(8, 7, 7)),

			new BlockOccupancy(new Vector3i(0, 7, 8)),
            new BlockOccupancy(new Vector3i(1, 7, 8)),
            new BlockOccupancy(new Vector3i(2, 7, 8)),
            new BlockOccupancy(new Vector3i(3, 7, 8)),
            new BlockOccupancy(new Vector3i(4, 7, 8)),
			new BlockOccupancy(new Vector3i(5, 7, 8)),
			new BlockOccupancy(new Vector3i(6, 7, 8)),
			new BlockOccupancy(new Vector3i(7, 7, 8)),
			new BlockOccupancy(new Vector3i(8, 7, 8)),

			new BlockOccupancy(new Vector3i(0, 7, 9)),
            new BlockOccupancy(new Vector3i(1, 7, 9)),
            new BlockOccupancy(new Vector3i(2, 7, 9)),
            new BlockOccupancy(new Vector3i(3, 7, 9)),
            new BlockOccupancy(new Vector3i(4, 7, 9)),
			new BlockOccupancy(new Vector3i(5, 7, 9)),
			new BlockOccupancy(new Vector3i(6, 7, 9)),
			new BlockOccupancy(new Vector3i(7, 7, 9)),
			new BlockOccupancy(new Vector3i(8, 7, 9)),

			new BlockOccupancy(new Vector3i(0, 7, 10)),
            new BlockOccupancy(new Vector3i(1, 7, 10)),
            new BlockOccupancy(new Vector3i(2, 7, 10)),
            new BlockOccupancy(new Vector3i(3, 7, 10)),
            new BlockOccupancy(new Vector3i(4, 7, 10)),
			new BlockOccupancy(new Vector3i(5, 7, 10)),
			new BlockOccupancy(new Vector3i(6, 7, 10)),
			new BlockOccupancy(new Vector3i(7, 7, 10)),
			new BlockOccupancy(new Vector3i(8, 7, 10)),

			new BlockOccupancy(new Vector3i(0, 7, 11)),
            new BlockOccupancy(new Vector3i(1, 7, 11)),
            new BlockOccupancy(new Vector3i(2, 7, 11)),
            new BlockOccupancy(new Vector3i(3, 7, 11)),
            new BlockOccupancy(new Vector3i(4, 7, 11)),
			new BlockOccupancy(new Vector3i(5, 7, 11)),
			new BlockOccupancy(new Vector3i(6, 7, 11)),
			new BlockOccupancy(new Vector3i(7, 7, 11)),
			new BlockOccupancy(new Vector3i(8, 7, 11)),

			new BlockOccupancy(new Vector3i(0, 7, 12)),
            new BlockOccupancy(new Vector3i(1, 7, 12)),
            new BlockOccupancy(new Vector3i(2, 7, 12)),
            new BlockOccupancy(new Vector3i(3, 7, 12)),
            new BlockOccupancy(new Vector3i(4, 7, 12)),
			new BlockOccupancy(new Vector3i(5, 7, 12)),
			new BlockOccupancy(new Vector3i(6, 7, 12)),
			new BlockOccupancy(new Vector3i(7, 7, 12)),
			new BlockOccupancy(new Vector3i(8, 7, 12)),
			
			new BlockOccupancy(new Vector3i(0, 7, 13)),
            new BlockOccupancy(new Vector3i(1, 7, 13)),
            new BlockOccupancy(new Vector3i(2, 7, 13)),
            new BlockOccupancy(new Vector3i(3, 7, 13)),
            new BlockOccupancy(new Vector3i(4, 7, 13)),
			new BlockOccupancy(new Vector3i(5, 7, 13)),
			new BlockOccupancy(new Vector3i(6, 7, 13)),
			new BlockOccupancy(new Vector3i(7, 7, 13)),
			new BlockOccupancy(new Vector3i(8, 7, 13)),

			#endregion
//////////////////////////////////////5x5x13Back//////////////////////////////////////
			};

            AddOccupancy<CattleBarnObject>(BlockOccupancyList);
		} 

        protected override void Initialize()
        {
            this.ModsPreInitialize();
            this.GetComponent<MinimapComponent>().SetCategory(Localizer.DoStr("Crafting"));

            this.ModsPostInitialize();
        }
        

        [Interaction(InteractionTrigger.RightClick, "Open Door")]
        public void OpenDoor(Player context, InteractionTriggerInfo interactionTriggerInfo, InteractionTarget interactionTarget)
        {
            var isAuthorized = ServiceHolder<IAuthManager>.Obj.IsAuthorized(this, context.User);

            if (isAuthorized)
            {
                OpenDoors = !OpenDoors;
            }
            else
            {
                context.ErrorLocStr("You Are Not Authorized To Do That");
                return;
            }
        }

        public override void Tick()
        {
            base.Tick();
            SetAnimatedState("OpenDoor", OpenDoors);
        }

        /// <summary>Hook for mods to customize WorldObject before initialization. You can change housing values here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize WorldObject after initialization.</summary>
        partial void ModsPostInitialize();

//Added Storage

            protected override void PostInitialize()
        {
            base.PostInitialize();
  
            var storage = this.GetComponent<PublicStorageComponent>();
            // Number of slots
            storage.Initialize(20);
            // Stack Limit
            storage.Storage.AddInvRestriction(new StockpileStackRestriction(100)); // limit stack sizes to the y-height of the LumberStockpile
            // storage range
            this.GetComponent<LinkComponent>().Initialize(12);
        }


    }

    [Serialized]
    [LocDisplayName("Cattle Barn")]
    [LocDescription("Greenhouse for farming larger amounts of crops quickly.")]
    [IconGroup("World Object Minimap")]
    [Ecopedia("Work Stations", "Craft Tables", createAsSubPage: true)]
    [Tag("Crafting Table")]
    [Weight(5000)] // Defines how heavy CattleBarn is.
	[MaxStackSize(200)]
    [AllowPluginModules(Tags = new[] { "BasicUpgrade" }, ItemTypes = new[] { typeof(HuntingUpgradeItem) })] //noloc
    public partial class CattleBarnItem : WorldObjectItem<CattleBarnObject>, IPersistentData
    {
        protected override OccupancyContext GetOccupancyContext => new SideAttachedContext( 0  | DirectionAxisFlags.Down , WorldObject.GetOccupancyInfo(this.WorldObjectType));



        [Serialized, SyncToView, NewTooltipChildren(CacheAs.Instance, flags: TTFlags.AllowNonControllerTypeForChildren)] public object PersistentData { get; set; }
    }

    /// <summary>
    /// <para>Server side recipe definition for "CattleBarn".</para>
    /// <para>More information about RecipeFamily objects can be found at https://docs.play.eco/api/server/eco.gameplay/Eco.Gameplay.Items.RecipeFamily.html</para>
    /// </summary>
    /// <remarks>
    /// This is an auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization. 
    /// If you wish to modify this class, please create a new partial class or follow the instructions in the "UserCode" folder to override the entire file.
    /// </remarks>
    [RequiresSkill(typeof(CarpentrySkill), 1)]
    [Ecopedia("Work Stations", "Craft Tables", subPageName: "CattleBarn Item")]
    public partial class CattleBarnRecipe : RecipeFamily
    {
        public CattleBarnRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "CattleBarn",  //noloc
                displayName: Localizer.DoStr("Cattle Barn"),

                // Defines the ingredients needed to craft this recipe. An ingredient items takes the following inputs
                // type of the item, the amount of the item, the skill required, and the talent used.
                ingredients: new List<IngredientElement>
                {
					new IngredientElement(typeof(GlassItem), 80, typeof(CarpentrySkill), typeof(CarpentryLavishResourcesTalent)),
                    new IngredientElement(typeof(NailItem), 60, typeof(CarpentrySkill), typeof(CarpentryLavishResourcesTalent)),
                    new IngredientElement("Lumber", 40, typeof(CarpentrySkill), typeof(CarpentryLavishResourcesTalent)), //noloc
                },

                // Define our recipe output items.
                // For every output item there needs to be one CraftingElement entry with the type of the final item and the amount
                // to create.
                items: new List<CraftingElement>
                {
                    new CraftingElement<CattleBarnItem>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 5; // Defines how much experience is gained when crafted.
            
            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(1000, typeof(CarpentrySkill));

            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(CattleBarnRecipe), start: 10, skillType: typeof(CarpentrySkill), typeof(CarpentryFocusedSpeedTalent), typeof(CarpentryParallelSpeedTalent));

            // Perform pre/post initialization for user mods and initialize our recipe instance with the display name "Cattle Barn"
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Cattle Barn"), recipeType: typeof(CattleBarnRecipe));
            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system so it can be crafted.
            CraftingComponent.AddRecipe(tableType: typeof(SawmillObject), recipe: this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();

        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
