// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from ItemTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

    [RequiresSkill(typeof(FarmingSkill), 4)]		// 2
    [Ecopedia("Items", "Products", subPageName: "Cotton Lint Item")]
    public partial class CottonLintBulkRecipe : RecipeFamily
    {
        public CottonLintBulkRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "CottonLintBulk",  //noloc
                displayName: Localizer.DoStr("Cotton Lint Bulk"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(CottonBollItem), 100, typeof(FarmingSkill)),	// 4 x 25
                },
                items: new List<CraftingElement>
                {
                    new CraftingElement<CottonLintItem>(75),	// 1 x 25 x 3
                    new CraftingElement<PlantFibersItem>(18.75f),	// 0.25 x 25 x 3
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 5f; // 0.2 x 25
            this.LaborInCalories = CreateLaborInCaloriesValue(875, typeof(FarmingSkill));	// 35 X 25
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(CottonLintBulkRecipe), start: 25, skillType: typeof(FarmingSkill));	// 1 X 25
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Cotton Lint Bulk"), recipeType: typeof(CottonLintBulkRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(tableType: typeof(FiberScutchingStationObject), recipe: this);
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}