// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from WorldObjectTemplate.tt />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Core.Items;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Components.Auth;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Economy;
    using Eco.Gameplay.Housing;
    using Eco.Gameplay.Interactions;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Modules;
    using Eco.Gameplay.Minimap;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Occupancy;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Property;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Gameplay.Pipes.LiquidComponents;
    using Eco.Gameplay.Pipes.Gases;
    using Eco.Shared;
    using Eco.Shared.Math;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;
    using Eco.Shared.Items;
    using Eco.Shared.Networking;
    using Eco.Gameplay.Pipes;
    using Eco.World.Blocks;
    using Eco.Gameplay.Housing.PropertyValues;
    using Eco.Gameplay.Civics.Objects;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems.NewTooltip;
    using Eco.Core.Controller;
    using Eco.Core.Utils;
	using Eco.Gameplay.Components.Storage;
    using Eco.Gameplay.Items.Recipes;

    [Serialized]
    [RequireComponent(typeof(PropertyAuthComponent))]
    [RequireComponent(typeof(HousingComponent))]
    [RequireComponent(typeof(ForSaleComponent))]
    [Tag("Usable")]
            public partial class ElkSkypiercerObject : WorldObject, IRepresentsItem
    {
        public virtual Type RepresentedItemType => typeof(ElkSkypiercerItem);
        public override LocString DisplayName => Localizer.DoStr("Elk Skypiercer");

        protected override void Initialize()
        {
            this.ModsPreInitialize();
            this.GetComponent<HousingComponent>().HomeValue = ElkSkypiercerItem.homeValue;
            this.ModsPostInitialize();
        }
protected override void OnCreatePostInitialize()
        {
            base.OnCreatePostInitialize();
            this.GetComponent<PropertyAuthComponent>().SetPublic();
        }
        /// <summary>Hook for mods to customize WorldObject before initialization. You can change housing values here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize WorldObject after initialization.</summary>
        partial void ModsPostInitialize();
    }

    [Serialized]
    [LocDisplayName("Elk Skypiercer")]
    [LocDescription("You can hear the faint cries of Ecko when this mythical elk antler is held aloft.")]
    [Ecopedia("Housing Objects", "Decoration", createAsSubPage: true)]
    [Tag("Housing")]
    [Weight(2000)]
            public partial class ElkSkypiercerItem : WorldObjectItem<ElkSkypiercerObject>
    {
        
        public override HomeFurnishingValue HomeValue => homeValue;
        public static readonly HomeFurnishingValue homeValue = new HomeFurnishingValue()
        {
            ObjectName                              = typeof(ElkSkypiercerObject).UILink(),
            Category                                = HousingConfig.GetRoomCategory("Decoration"),
            BaseValue                               = 10,
            TypeForRoomLimit                        = Localizer.DoStr("Taxidermy"),
            DiminishingReturnMultiplier             = 0.5f
            
        };
        
    }
    
    [RequiresSkill(typeof(HuntingSkill), 6)]
    [Ecopedia("Housing Objects", "Decoration", subPageName: "Elk Skypiercer")]
    public partial class ElkSkypiercerRecipe : RecipeFamily
    {
        public ElkSkypiercerRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "ElkSkypiercer",  //noloc
                displayName: Localizer.DoStr("Elk Skypiercer"),

                // Defines the ingredients needed to craft this recipe. An ingredient items takes the following inputs
                // type of the item, the amount of the item, the skill required, and the talent used.
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(ElkCarcassItem), 1, true),
                    new IngredientElement("Lumber", 5, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                    new IngredientElement(typeof(IronBarItem), 5, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                    new IngredientElement(typeof(BlackPowderItem), 100, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                    new IngredientElement(typeof(ColoredPowderItem), 100, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                    new IngredientElement(typeof(CyanPowderItem), 100, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                    new IngredientElement(typeof(MagentaPowderItem), 100, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                    new IngredientElement(typeof(CharcoalPowderItem), 100, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                    new IngredientElement(typeof(WhitePowderItem), 100, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                    new IngredientElement(typeof(YellowPowderItem), 100, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                    new IngredientElement(typeof(BluePowderItem), 100, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                    new IngredientElement(typeof(CopperHydroxideItem), 100, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                    new IngredientElement(typeof(IronOxideItem), 100, typeof(ButcherySkill), typeof(ButcheryLavishResourcesTalent)),
                },

                // Define our recipe output items.
                // For every output item there needs to be one CraftingElement entry with the type of the final item and the amount
                // to create.
                items: new List<CraftingElement>
                {
                    new CraftingElement<ElkSkypiercerItem>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 4; // Defines how much experience is gained when crafted.
            
            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(10000, typeof(HuntingSkill));

            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(ElkSkypiercerRecipe), start: 150, skillType: typeof(HuntingSkill));

            // Perform pre/post initialization for user mods and initialize our recipe instance with the display name "Stuffed Bison"
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Elk Skypiercer"), recipeType: typeof(ElkSkypiercerRecipe));
            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system so it can be crafted.
            CraftingComponent.AddRecipe(tableType: typeof(ButcheryTableObject), recipe: this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();

        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
   
